<!-- block best sellers -->
<div class="block left-module">
    <p class="title_block"><?php echo $translator->_('ON SALE')?></p>
    <div class="block_content product-onsale">
        <ul class="product-list owl-carousel" data-loop="true" data-nav = "false" data-margin = "0" data-autoplayTimeout="1000" data-autoplayHoverPause = "true" data-items="1" data-autoplay="true">
            <?php foreach ($products as $product) { ?>
                <li>
                    <div class="product-container">
                        <div class="left-block">
                            <a href="<?php echo $product['href']; ?>">
                                <img class="img-responsive" alt="product" src="<?php echo $product['thumb']; ?>" />
                            </a>
                            <div class="price-percent-reduction2">-<?php echo $product['special_percent']?>% <?php echo $translator->_('OFF')?></div>
                        </div>
                        <div class="right-block">
                            <h5 class="product-name"><a href="<?php echo $product['href']; ?>"><?php echo $product['name']; ?></a></h5>
                            <div class="product-star">
                                <?php for ($i = 1; $i <= $product['rating']; $i++) { ?>
                                    <i class="fa fa-star"></i>
                                    <?php if($product['rating'] == $i && $product['rating'] < 5) {?>
                                        <i class="fa fa-star-half-o"></i>
                                    <?php }?>
                                <?php } ?>

                            </div>
                            <?php if ($product['price']) { ?>
                                <p class="price">
                                    <span class="price product-price"><?php echo $product['special']; ?></span>
                                    <span class="price old-price"><?php echo $product['price']; ?></span>
                                </p>
                            <?php } ?>
                        </div>
                        <div class="product-bottom">
                            <a class="btn-add-cart" title="<?php echo $translator->_('Add to Cart')?>" href="javascript:;" onclick="cart.add('<?php echo $product['product_id']; ?>');"><?php echo $translator->_('Add to Cart')?></a>
                        </div>
                    </div>
                </li>
            <?php } ?>
        </ul>
    </div>
</div>
<!-- ./block best sellers  -->