<?php if(count($custom_menu) > 0) { ?>
<div id="box-vertical-megamenus" <?php echo (isset($display_vertical_menu) ? $display_vertical_menu : '')?>>
<div class="box-vertical-megamenus opt<?php echo $layout_id?>">
    <div class="vertical-menu-content is-home">
        <ul class="vertical-menu-list">
            <?php foreach($custom_menu as $menu) {?>
                <li>
                    <a class="<?php echo (isset($menu['children']) && is_array($menu['children']) > 0 ? 'parent' : '');?>" href="<?php echo (isset($menu['link']) ? $menu['link'] : '#')?>"><span class="icon-menu <?php echo (isset($menu['icon']) ? $menu['icon'] : 'mif-sunrise')?>"></span><?php echo $menu['title']?></a>
                    <?php if(isset($menu['children']) && is_array($menu['children']) > 0){ ?>
                        <div class="vertical-dropdown-menu">
                            <div class="vertical-groups col-sm-12">
                                <?php foreach($menu['children'] as $child_menu) {?>
                                    <div class="mega-group col-sm-4">
                                        <h4 class="mega-group-header"><span><?php echo $child_menu['title']?></span></h4>
                                        <?php if(isset($child_menu['children']) && count($child_menu['children']) > 0){ ?>
                                            <ul class="group-link-default">
                                                <?php foreach($child_menu['children'] as $sub_child_menu) {?>
                                                    <li><a href="<?php echo (isset($sub_child_menu['link']) ? $sub_child_menu['link'] : '#')?>"><?php echo $sub_child_menu['title']?></a></li>
                                                <?php } ?>
                                            </ul>
                                        <?php } ?>
                                    </div>
                                <?php } ?>
                            </div>
                        </div>
                    <?php } ?>
                </li>
            <?php } ?>
        </ul>
        <div class="all-category"><span class="open-cate"><?php echo $translator->_('All Categories'); ?></span></div>
    </div>
</div>
</div>
<?php } ?>