<div class="introduce-title"><?php echo $translator->_("Let's Socialize")?></div>

<div class="social-link">
    <a href="<?php echo $social_links['facebook']?>"><i class="fa fa-facebook"></i></a>
    <a href="<?php echo $social_links['pinterest']?>"><i class="fa fa-pinterest"></i></a>
    <a href="<?php echo $social_links['vk']?>"><i class="fa fa-vk"></i></a>
    <a href="<?php echo $social_links['twitter']?>"><i class="fa fa-twitter"></i></a>
    <a href="<?php echo $social_links['gplus']?>"><i class="fa fa-google-plus"></i></a>
</div>