<!-- HEADER -->
<div id="header" class="header header8">
    <div class="top-header">
        <div class="container">
            <div class="nav-top-links">
                <a class="first-item" href="#">Welcome to KuteShop</a>
                <a href="#">Call Us: +09 957774334</a>
            </div>
            <a class="btn-fb-login" href="#">Login fb</a>
            <div class="icon-cart-top"><a  href="#"><i class="fa fa-shopping-cart"></i></a></div>
            <div class="user-info">
                <div class="dropdown">
                    <a class="current-open" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" href="#"><i class="fa fa-user"></i></a>
                    <ul class="dropdown-menu mega_dropdown" role="menu">
                        <li><a href="login.html">Login</a></li>
                        <li><a href="#">Compare</a></li>
                        <li><a href="#">Wishlists</a></li>
                    </ul>
                </div>
            </div>
            <div class="form-search">
                <span class="icon fa fa-search"></span>
                <div class="form">
                    <input type="text" placeholder="Keyword here...">
                    <i class="close-form fa fa-times"></i>
                </div>
            </div>

            <div class="currency ">
                <div class="dropdown">
                      <a class="current-open" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="#">USD</a>
                      <ul class="dropdown-menu" role="menu">
                        <li><a href="#">Dollar</a></li>
                        <li><a href="#">Euro</a></li>
                      </ul>
                </div>
            </div>
            <div class="language ">
                <div class="dropdown">
                      <a class="current-open" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="#">
                      <img alt="email" src="catalog/view/theme/kute/images/fr.jpg">French
                      
                      </a>
                      <ul class="dropdown-menu" role="menu">
                        <li><a href="#"><img alt="email" src="catalog/view/theme/kute/images/en.jpg">English</a></li>
                        <li><a href="#"><img alt="email" src="catalog/view/theme/kute/images/fr.jpg">French</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!--/.top-header -->
    <!-- MAIN HEADER -->
    <div id="main-header">
        <div class="container main-header">
            <div class="row">
                <div class="col-xs-12 col-sm-3 col-lg-3 logo">
                    <a href="index.html"><img alt="Kute Shop" src="catalog/view/theme/kute/images/data/option8/logo.png" /></a>
                </div>
                <div class="col-sm-10 col-md-7 col-lg-8 main-menu-wapper">
                    <div id="main-menu" class="main-menu">
                        <nav class="navbar navbar-default">
                            <div class="container-fluid">
                                <div class="navbar-header">
                                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                                        <i class="fa fa-bars"></i>
                                    </button>
                                    <a class="navbar-brand" href="#">MENU</a>
                                </div>
                                <div id="navbar" class="navbar-collapse collapse">
                                    <ul class="nav navbar-nav">
                                        <li class="active"><a href="#">Home</a></li>
                                        <li class="dropdown">
                                            <a href="category.html" class="dropdown-toggle" data-toggle="dropdown">MEN</a>
                                            <ul class="dropdown-menu mega_dropdown" role="menu" style="width: 830px;">
                                                <li class="block-container col-sm-3">
                                                    <ul class="block">
                                                        <li class="img_container">
                                                            <a href="#">
                                                                <img class="img-responsive" src="catalog/view/theme/kute/images/data/men.png" alt="sport">
                                                            </a>
                                                        </li>
                                                        <li class="link_container group_header">
                                                            <a href="#">MEN'S</a>
                                                        </li>
                                                        <li class="link_container"><a href="#">Skirts</a></li>
                                                        <li class="link_container"><a href="#">Jackets</a></li>
                                                        <li class="link_container"><a href="#">Tops</a></li>
                                                        <li class="link_container"><a href="#">Scarves</a></li>
                                                        <li class="link_container"><a href="#">Pants</a></li>
                                                    </ul>
                                                </li>
                                                 <li class="block-container col-sm-3">
                                                    <ul class="block">
                                                        <li class="img_container">
                                                            <a href="#">
                                                                <img class="img-responsive" src="catalog/view/theme/kute/images/data/women.png" alt="sport">
                                                            </a>
                                                        </li>
                                                        <li class="link_container group_header">
                                                            <a href="#">WOMEN'S</a>
                                                        </li>
                                                        <li class="link_container"><a href="#">Skirts</a></li>
                                                        <li class="link_container"><a href="#">Jackets</a></li>
                                                        <li class="link_container"><a href="#">Tops</a></li>
                                                        <li class="link_container"><a href="#">Scarves</a></li>
                                                        <li class="link_container"><a href="#">Pants</a></li>
                                                    </ul>
                                                </li>
                                                 <li class="block-container col-sm-3">
                                                    <ul class="block">
                                                        <li class="img_container">
                                                            <a href="#">
                                                                <img class="img-responsive" src="catalog/view/theme/kute/images/data/kid.png" alt="sport">
                                                            </a>
                                                        </li>
                                                        <li class="link_container group_header">
                                                            <a href="#">Kids</a>
                                                        </li>
                                                        <li class="link_container"><a href="#">Shoes</a></li>
                                                        <li class="link_container"><a href="#">Clothing</a></li>
                                                        <li class="link_container"><a href="#">Tops</a></li>
                                                        <li class="link_container"><a href="#">Scarves</a></li>
                                                        <li class="link_container"><a href="#">Accessories</a></li>
                                                    </ul>
                                                </li>
                                                 <li class="block-container col-sm-3">
                                                    <ul class="block">
                                                        <li class="img_container">
                                                            <a href="#">
                                                                <img class="img-responsive" src="catalog/view/theme/kute/images/data/trending.png" alt="sport">
                                                            </a>
                                                        </li>
                                                        <li class="link_container group_header">
                                                            <a href="#">TRENDING</a>
                                                        </li>
                                                        <li class="link_container"><a href="#">Men's Clothing</a></li>
                                                        <li class="link_container"><a href="#">Kid's Clothing</a></li>
                                                        <li class="link_container"><a href="#">Women's Clothing</a></li>
                                                        <li class="link_container"><a href="#">Accessories</a></li>
                                                    </ul>
                                                </li>
                                            </ul>
                                        </li>
                                        <li><a href="category.html" class="dropdown-toggle" data-toggle="dropdown">WOMEN</a></li>
                                        <li class="dropdown">
                                            <a href="category.html" class="dropdown-toggle" data-toggle="dropdown">KIDS</a>
                                                <ul class="mega_dropdown dropdown-menu" style="width: 830px;">
                                                <li class="block-container col-sm-3">
                                                    <ul class="block">
                                                        <li class="link_container group_header">
                                                            <a href="#">Asian</a>
                                                        </li>
                                                        <li class="link_container">
                                                            <a href="#">Vietnamese Pho</a>
                                                        </li>
                                                        <li class="link_container">
                                                            <a href="#">Noodles</a>
                                                        </li>
                                                        <li class="link_container">
                                                            <a href="#">Seafood</a>
                                                        </li>
                                                        <li class="link_container group_header">
                                                            <a href="#">Sausages</a>
                                                        </li>
                                                        <li class="link_container">
                                                            <a href="#">Meat Dishes</a>
                                                        </li>
                                                        <li class="link_container">
                                                            <a href="#">Desserts</a>
                                                        </li>
                                                        <li class="link_container">
                                                            <a href="#">Tops</a>
                                                        </li>
                                                        <li class="link_container">
                                                            <a href="#">Tops</a>
                                                        </li>
                                                    </ul>
                                                </li>
                                                <li class="block-container col-sm-3">
                                                    <ul class="block">
                                                        <li class="link_container group_header">
                                                            <a href="#">European</a>
                                                        </li>
                                                        <li class="link_container">
                                                            <a href="#">Greek Potatoes</a>
                                                        </li>
                                                        <li class="link_container">
                                                            <a href="#">Famous Spaghetti</a>
                                                        </li>
                                                        <li class="link_container">
                                                            <a href="#">Famous Spaghetti</a>
                                                        </li>
                                                        <li class="link_container group_header">
                                                            <a href="#">Chicken</a>
                                                        </li>
                                                        <li class="link_container">
                                                            <a href="#">Italian Pizza</a>
                                                        </li>
                                                        <li class="link_container">
                                                            <a href="#">French Cakes</a>
                                                        </li>
                                                        <li class="link_container">
                                                            <a href="#">Tops</a>
                                                        </li>
                                                        <li class="link_container">
                                                            <a href="#">Tops</a>
                                                        </li>
                                                    </ul>
                                                </li>
                                                <li class="block-container col-sm-3">
                                                    <ul class="block">
                                                        <li class="link_container group_header">
                                                            <a href="#">FAST</a>
                                                        </li>
                                                        <li class="link_container">
                                                            <a href="#">Hamberger</a>
                                                        </li>
                                                        <li class="link_container">
                                                            <a href="#">Pizza</a>
                                                        </li>
                                                        <li class="link_container">
                                                            <a href="#">Noodles</a>
                                                        </li>
                                                        <li class="link_container group_header">
                                                            <a href="#">Sandwich</a>
                                                        </li>
                                                        <li class="link_container">
                                                            <a href="#">Salad</a>
                                                        </li>
                                                        <li class="link_container">
                                                            <a href="#">Paste</a>
                                                        </li>
                                                        <li class="link_container">
                                                            <a href="#">Tops</a>
                                                        </li>
                                                        <li class="link_container">
                                                            <a href="#">Tops</a>
                                                        </li>
                                                    </ul>
                                                </li>
                                                <li class="block-container col-sm-3">
                                                    <ul class="block">
                                                        <li class="img_container">
                                                            <img src="catalog/view/theme/kute/images/data/banner-topmenu.jpg" alt="Banner">
                                                        </li>
                                                    </ul>
                                                </li>

                                            </ul>
                                        </li>
                                        <li class="dropdown">
                                            <a href="category.html" class="dropdown-toggle" data-toggle="dropdown">ACCESSORIES</a>
                                            <ul class="dropdown-menu container-fluid">
                                                <li class="block-container">
                                                    <ul class="block">
                                                        <li class="link_container"><a href="#">Mobile</a></li>
                                                        <li class="link_container"><a href="#">Tablets</a></li>
                                                        <li class="link_container"><a href="#">Laptop</a></li>
                                                        <li class="link_container"><a href="#">Memory Cards</a></li>
                                                        <li class="link_container"><a href="#">Accessories</a></li>
                                                    </ul>
                                                </li>
                                            </ul> 
                                        </li>
                                        <li><a href="category.html">BRANDS</a></li>
                                        <li><a href="category.html">Blog</a></li>
                                    </ul>
                                </div><!--/.nav-collapse -->
                            </div>
                        </nav>
                    </div>
                </div>
                <div class="col-sm-2 col-md-2 col-lg-1 group-button-header">
                    <div class="btn-cart" id="cart-block">
                        <a title="My cart" href="cart.html">My Cart</a>
                        <span class="notify notify-right">10</span>
                        <div class="cart-block">
                            <div class="cart-block-content">
                                <h5 class="cart-title">2 Items in my cart</h5>
                                <div class="cart-block-list">
                                    <ul>
                                        <li class="product-info">
                                            <div class="p-left">
                                                <a href="#" class="remove_link"></a>
                                                <a href="#">
                                                <img class="img-responsive" src="catalog/view/theme/kute/images/data/product-100x122.jpg" alt="p10">
                                                </a>
                                            </div>
                                            <div class="p-right">
                                                <p class="p-name">Donec Ac Tempus</p>
                                                <p class="p-rice">61,19 €</p>
                                                <p>Qty: 1</p>
                                            </div>
                                        </li>
                                        <li class="product-info">
                                            <div class="p-left">
                                                <a href="#" class="remove_link"></a>
                                                <a href="#">
                                                <img class="img-responsive" src="catalog/view/theme/kute/images/data/product-s5-100x122.jpg" alt="p10">
                                                </a>
                                            </div>
                                            <div class="p-right">
                                                <p class="p-name">Donec Ac Tempus</p>
                                                <p class="p-rice">61,19 €</p>
                                                <p>Qty: 1</p>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                                <div class="toal-cart">
                                    <span>Total</span>
                                    <span class="toal-price pull-right">122.38 €</span>
                                </div>
                                <div class="cart-buttons">
                                    <a href="order.html" class="btn-check-out">Checkout</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- END MANIN HEADER -->
</div>
<!-- end header -->