
<!-- Footer -->
<footer id="footer2">
     <div class="footer-top">
         <div class="container">
             <div class="row">
                 <div class="col-sm-3">
                     <div class="footer-logo">
                         <a href="#"><img src="catalog/view/theme/kute/images/data/option7/logo2.png" alt="Logo"></a>
                     </div>
                 </div>
                 <div class="col-sm-12 col-md-6">
                     <div class="footer-menu">       
                         <ul>
                             <li><a href="#">About Us</a></li>
                             <li><a href="#">Affiliates</a></li>
                             <li><a href="#">Careers</a></li>
                             <li><a href="#">Privacy Plocy</a></li>
                             <li><a href="#">Terms of Use</a></li>
                             <li><a href="#">Contact Us</a></li>
                         </ul>
                     </div>
                 </div>
                 <div class="col-sm-12 col-md-3">
                     <div class="form-newsletter">
                         <input placeholder="Please enter your email" class="form-newsletter-input" type="text">
                         <button class="form-newsletter-button">OK</button>
                     </div>
                 </div>
             </div>
         </div>
     </div>

     <!-- footer paralax-->
     <div class="footer-row">
             <div class="container">
                 <div class="row">
                     <div class="col-sm-6 col-md-3">
                         <div class="widget-container widget-contact-info">
                             <h3 class="widget-title">Infomation</h3>
                             <div class="widget-body">
                                 <ul>
                                     <li><a class="location" href="#"><span class="address">Address:</span>2046 Blue Spruce Lane Laurel, tetxac, Orton Tolanto, Canada</a></li>
                                     <li><a class="phone" href="#"><span>Phone:</span>0200 410-369-3920</a></li>
                                     <li><a class="mobile" href="#"><span>Hotline:</span> 090 999 8686</a></li>
                                     <li><a class="email" href="#"><span>Email:</span>nfo@kutethemes.com</a></li>
                                 </ul>
                             </div>
                         </div>
                     </div>
                     <div class="col-sm-3 col-md-2">
                         <div class="widget-container">
                             <h3 class="widget-title">COMPANY</h3>
                             <div class="widget-body">
                                 <ul>
                                     <li><a href="#">About Us</a></li>
                                     <li><a href="#">Testimonials</a></li>
                                     <li><a href="#">Affiliate Program</a></li>
                                     <li><a href="#">Terms & Conditions</a></li>
                                     <li><a href="#">Contact Us</a></li>
                                 </ul>
                             </div>
                         </div>
                     </div>
                     <div class="col-sm-3 col-md-2">
                         <div class="widget-container">
                             <h3 class="widget-title">my account</h3>
                             <div class="widget-body">
                                 <ul>
                                     <li><a href="#">My Orders</a></li>
                                     <li><a href="#">My Credit Slips</a></li>
                                     <li><a href="#">My Addresses</a></li>
                                     <li><a href="#">My Personal Info</a></li>
                                     <li><a href="#">Specials</a></li>
                                 </ul>
                             </div>
                         </div>
                     </div>
                     <div class="col-sm-6 col-md-2">
                         <div class="widget-container">
                             <h3 class="widget-title">SUPPORT</h3>
                             <div class="widget-body">
                                 <ul>
                                     <li><a href="#">Payments</a></li>
                                     <li><a href="#">Saved Cards</a></li>
                                     <li><a href="#">Shipping Free</a></li>
                                     <li><a href="#">Cancellation</a></li>
                                     <li><a href="#">Support Online</a></li>
                                 </ul>
                             </div>
                         </div>
                     </div>
                     <div class="col-sm-6 col-md-3">
                         <div class="widget-container">
                             <h3 class="widget-title">Let's Socialize</h3>
                             <div class="widget-body">
                                 <div class="footer-social">
                                     <ul>
                                         <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
                                         <li><a class="pinterest" href="#"><i class="fa fa-pinterest-p"></i></a></li>
                                         <li><a class="vk" href="#"><i class="fa fa-vk"></i></a></li>
                                         <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
                                         <li><a class="google-plus" href="#"><i class="fa fa-google-plus"></i></a></li>
                                     </ul>
                                 </div>
                             </div>
                         </div>
                         <div class="widget-container">
                             <h3 class="widget-title">payment</h3>
                             <div class="widget-body">
                                 <img src="catalog/view/theme/kute/images/data/option7/payment.png" alt="Payment">
                             </div>
                         </div>
                     </div>
                 </div>
             </div>
         </div>
     <div class="footer-bottom">
             <div class="container">
                 <div class="footer-bottom-wapper">
                     <div class="row">
                         <div class="col-sm-12">
                             <div class="footer-coppyright">
                                 Copyright © 2015 KuteShop. All Rights Reserved. Designed by: KuteThemes
                             </div>

                         </div>
                     </div>
                 </div>
             </div>
         </div>
     <!-- ./footer paralax-->
</footer>
