<!-- Footer -->
<footer id="footer2">
     <div class="footer-top">
         <div class="container">
             <div class="row">
                 <div class="col-sm-3">
                     <div class="footer-logo">
                         <a href="#"><img src="image/catalog/option4/logo3.png" alt="Logo"></a>
                     </div>
                 </div>
                 <div class="col-sm-6">
                     <div class="footer-menu">       
                         <ul>
                             <li><a href="#">About Us</a></li>
                             <li><a href="#">Affiliates</a></li>
                             <li><a href="#">Careers</a></li>
                             <li><a href="#">Privacy Policy</a></li>
                             <li><a href="#">Terms of Use</a></li>
                             <li><a href="#">Contact Us</a></li>
                         </ul>
                     </div>
                 </div>
                 <?php echo $Loader->block('common/footer_'.$current_theme.'_social')->setTemplate('footer/child/social.phtml')->setData($data)->toHtml(); ?>
             </div>
         </div>
     </div>

     <!-- footer paralax-->
     <div class="footer-paralax">
         <div class="footer-row footer-center">
             <div class="container">
                 <h3>Sign up below for early updates</h3>
                 <p>You a Client , large or small, and want to participate in this adventure, please send us an email to support@kuteshop.com</p>                 <div class="form-inline form-subscribe">
                      <div class="form-group box-newsletter-subscribe">
                        <input type="text" name="email" class="form-control" placeholder="Enter Your E-mail Address">
                        <button type="submit" class="btn btn-default enter-subscribe"><i class="fa fa-paper-plane-o"></i></button>
                      </div>
                    
                </div>
             </div>
         </div>
         <div class="footer-row">
             <div class="container">
                 <div class="row">
                     <?php echo $Loader->block('common/footer_'.$current_theme.'_address')->setTemplate('footer/child/address.phtml')->setData($data)->toHtml(); ?>
                     <?php if ($informations) { ?>
                     <div class="col-sm-3">
                         <div class="widget-container">
                             <h3 class="widget-title"><?php echo $text_information; ?></h3>
                             <div class="widget-body">
                                 <ul>
                                    <?php foreach ($informations as $information) { ?>
                                        <li><a href="<?php echo $information['href']; ?>"><?php echo $information['title']; ?></a></li>
                                    <?php } ?>
                                 </ul>
                             </div>
                         </div>
                     </div>
                     <?php } ?>
                     <div class="col-sm-3">
                         <div class="widget-container">
                             <h3 class="widget-title"><?php echo $text_service; ?></h3>
                             <div class="widget-body">
                                 <ul>
                                    <li><a href="<?php echo $contact; ?>"><?php echo $text_contact; ?></a></li>
                                    <li><a href="<?php echo $return; ?>"><?php echo $text_return; ?></a></li>
                                    <li><a href="<?php echo $sitemap; ?>"><?php echo $text_sitemap; ?></a></li>
                                 </ul>
                             </div>
                         </div>
                     </div>
                     <div class="col-sm-3">
                         <div class="widget-container">
                             <h3 class="widget-title"><?php echo $text_extra; ?></h3>
                             <div class="widget-body">
                                 <ul>
                                    <li><a href="<?php echo $manufacturer; ?>"><?php echo $text_manufacturer; ?></a></li>
                                    <li><a href="<?php echo $voucher; ?>"><?php echo $text_voucher; ?></a></li>
                                    <li><a href="<?php echo $affiliate; ?>"><?php echo $text_affiliate; ?></a></li>
                                    <li><a href="<?php echo $special; ?>"><?php echo $text_special; ?></a></li>
                                 </ul>
                             </div>
                         </div>
                     </div>
                 </div>
             </div>
         </div>
         <div class="footer-bottom">
             <div class="container">
                 <div class="footer-bottom-wapper">
                     <div class="row">
                         <div class="col-sm-8">
                             <div class="footer-coppyright">
                                 <?php echo $translator->_('Copyrights'); ?>
                             </div>

                         </div>
                         <?php echo $Loader->block('common/footer_'.$current_theme.'_payment')->setTemplate('footer/child/payment.phtml')->setData($data)->toHtml(); ?>
                     </div>
                 </div>
             </div>
         </div>
     </div>
     <!-- ./footer paralax-->
</footer>
<script type="text/javascript" src="catalog/view/theme/kute/js/countdown/jquery.plugin.js"></script>
<script type="text/javascript" src="catalog/view/theme/kute/js/countdown/jquery.countdown.js"></script>
<script type="text/javascript" src="catalog/view/theme/kute/js/theme-script.js"></script>
<script type="text/javascript" src="catalog/view/theme/kute/js/option4.js"></script>