<?php echo $header; ?>
<div id="columns" class="container" >
    <ul class="breadcrumb">
        <?php foreach ($breadcrumbs as $breadcrumb) { ?>
            <li><a href="<?php echo $breadcrumb['href']; ?>"><?php echo $breadcrumb['text']; ?></a></li>
        <?php } ?>
    </ul>
    <div class="row"><?php echo $column_left; ?>
        <?php if ($column_left && $column_right) { ?>
            <?php $class = 'col-sm-6'; ?>
        <?php } elseif ($column_left || $column_right) { ?>
            <?php $class = 'center_column col-xs-12 col-sm-9'; ?>
        <?php } else { ?>
            <?php $class = 'col-sm-12'; ?>
        <?php } ?>
        <div id="content" class="<?php echo $class; ?>">
            <!-- category-slider -->
            <?php echo $content_top; ?>
            <?php if ($categories) { ?>
                
                    <div class="subcategories">
                        <ul>
                            <li class="current-categorie">
                                <a href="#"><?php echo $heading_title; ?></a>
                            </li>
                            <?php $i=0; foreach ($categories as $category) { ?>
                                <?php $i=$i+1; if($i<5){?>
                                <li><a href="<?php echo $category['href']; ?>"><?php echo $category['name']; ?></a></li>
                            <?php } } ?>
                        </ul>
                    </div>
                
            <?php } ?>
            <div id="view-product-list" class="view-product-list">
            <?php if ($products) { ?>
                <h2 class="page-heading">
                    <span class="page-heading-title"><?php echo $heading_title; ?></span>
                </h2>
                <ul class="display-product-option">
                    <li class="view-as-grid selected"><span id="grid-view" data-toggle="tooltip" title="<?php echo $button_grid; ?>"><i class="fa fa-th"></i></span></li>
                    <li class="view-as-list"><span id="list-view" data-toggle="tooltip" title="<?php echo $button_list; ?>"><i class="fa fa-th-list"></i></span></li>
                </ul>
                <ul class="row product-list grid">
                    <?php echo $products_list_html?>
                </ul>
                <div class="sortPagiBar">
                    <div class="bottom-pagination"><?php echo $pagination; ?></div>
                    <div class="show-product-item">
                        <select id="input-limit" onchange="location = this.value;">
                            <?php foreach ($limits as $limits) { ?>
                                <?php if ($limits['value'] == $limit) { ?>
                                    <option value="<?php echo $limits['href']; ?>" selected="selected"><?php echo 'Show '.$limits['text']; ?></option>
                                <?php } else { ?>
                                    <option value="<?php echo $limits['href']; ?>"><?php echo $limits['text']; ?></option>
                                <?php } ?>
                            <?php } ?>
                        </select>
                    </div>
                    <div class="sort-product">
                        <select id="input-sort" onchange="location = this.value;">
                            <?php foreach ($sorts as $sorts) { ?>
                                <?php if ($sorts['value'] == $sort . '-' . $order) { ?>
                                    <option value="<?php echo $sorts['href']; ?>" selected="selected"><?php echo $sorts['text']; ?></option>
                                <?php } else { ?>
                                    <option value="<?php echo $sorts['href']; ?>"><?php echo $sorts['text']; ?></option>
                                <?php } ?>
                            <?php } ?>
                        </select>
                        <div class="sort-product-icon">
                            <i class="fa fa-sort-alpha-asc"></i>
                        </div>
                    </div>
                </div>
            </div>
            <?php } ?>
        </div>
        <?php if (!$categories && !$products) { ?>
            <p><?php echo $text_empty; ?></p>
            <div class="buttons">
                <div class="pull-right"><a href="<?php echo $continue; ?>" class="btn btn-primary"><?php echo $button_continue; ?></a></div>
            </div>
        <?php } ?>
        <?php echo $content_bottom; ?></div>
    <?php echo $column_right; ?></div>
<?php echo $footer; ?>
