<?php if ($products) { ?>
    <h2 class="page-heading">
        <span class="page-heading-title"><?php echo $heading_title; ?></span>
    </h2>
    <ul class="display-product-option">
        <li class="view-as-grid selected"><span id="grid-view" data-toggle="tooltip" title="<?php echo $button_grid; ?>"><i class="fa fa-th"></i></span></li>
        <li class="view-as-list"><span id="list-view" data-toggle="tooltip" title="<?php echo $button_list; ?>"><i class="fa fa-th-list"></i></span></li>
    </ul>
    <ul class="row product-list grid">
        <?php echo $products_list_html?>
    </ul>
    <div class="sortPagiBar">
        <div class="bottom-pagination"><?php echo $pagination; ?></div>
        <div class="show-product-item">
            <select id="input-limit" onchange="location = this.value;">
                <?php foreach ($limits as $limits) { ?>
                    <?php if ($limits['value'] == $limit) { ?>
                        <option value="<?php echo $limits['href']; ?>" selected="selected"><?php echo 'Show '.$limits['text']; ?></option>
                    <?php } else { ?>
                        <option value="<?php echo $limits['href']; ?>"><?php echo $limits['text']; ?></option>
                    <?php } ?>
                <?php } ?>
            </select>
        </div>
        <div class="sort-product">
            <select id="input-sort" onchange="location = this.value;">
                <?php foreach ($sorts as $sorts) { ?>
                    <?php if ($sorts['value'] == $sort . '-' . $order) { ?>
                        <option value="<?php echo $sorts['href']; ?>" selected="selected"><?php echo $sorts['text']; ?></option>
                    <?php } else { ?>
                        <option value="<?php echo $sorts['href']; ?>"><?php echo $sorts['text']; ?></option>
                    <?php } ?>
                <?php } ?>
            </select>
            <div class="sort-product-icon">
                <i class="fa fa-sort-alpha-asc"></i>
            </div>
        </div>
    </div>
</div>
<?php } ?>
