<?php echo $header; ?>
    <div id="columns" class="container">
        <ul class="breadcrumb">
            <?php foreach ($breadcrumbs as $breadcrumb) { ?>
                <li><a href="<?php echo $breadcrumb['href']; ?>"><?php echo $breadcrumb['text']; ?></a></li>
            <?php } ?>
        </ul>
        <div class="row"><?php echo $column_left; ?>
            <?php if ($column_left && $column_right) { ?>
                <?php $class = 'col-sm-6'; ?>
            <?php } elseif ($column_left || $column_right) { ?>
                <?php $class = 'center_column col-xs-12 col-sm-9'; ?>
            <?php } else { ?>
                <?php $class = 'col-sm-12'; ?>
            <?php } ?>
            <div id="content" class="<?php echo $class; ?>"><?php echo $content_top; ?>
                <div id="product">
                    <div class="primary-box row">
                        <?php if ($column_left && $column_right) { ?>
                            <?php $class = 'col-sm-6'; ?>
                        <?php } elseif ($column_left || $column_right) { ?>
                            <?php $class = 'pb-left-column col-xs-12 col-sm-6'; ?>
                        <?php } else { ?>
                            <?php $class = 'pb-left-column col-sm-8'; ?>
                        <?php } ?>
                        <div class="<?php echo $class; ?>">
                            <!-- product-imge-->
                            <div class="product-image">
                                <?php if ($thumb || $images) { ?>
                                    <?php if ($thumb) { ?>
                                        <div class="product-full">
                                            <img id="product-zoom" src="<?php echo $thumb; ?>" title="<?php echo $heading_title; ?>" data-zoom-image="<?php echo $popup; ?>" alt="<?php echo $heading_title; ?>" />
                                        </div>
                                    <?php } ?>
                                    <?php if ($images) { ?>
                                        <div class="product-img-thumb" id="gallery_01">
                                            <ul class="owl-carousel" data-items="3" data-nav="true" data-dots="false" data-margin="20" data-loop="false">
                                                <?php foreach ($images as $image) { ?>
                                                    <li>
                                                        <a data-image="<?php echo $image['popup']; ?>" data-zoom-image="<?php echo $image['popup']; ?>" title="<?php echo $heading_title; ?>">
                                                            <img src="<?php echo $image['thumb']; ?>" title="<?php echo $heading_title; ?>" alt="<?php echo $heading_title; ?>" /></a></li>
                                                <?php } ?>
                                            </ul>
                                        </div>
                                    <?php } ?>
                                <?php } ?>
                            </div>
                            <!-- product-imge-->

                        </div>
                        <?php if ($column_left && $column_right) { ?>
                            <?php $class = 'pb-left-column col-xs-12 col-sm-6'; ?>
                        <?php } elseif ($column_left || $column_right) { ?>
                            <?php $class = 'pb-right-column col-xs-12 col-sm-6'; ?>
                        <?php } else { ?>
                            <?php $class = 'pb-right-column col-sm-4'; ?>
                        <?php } ?>
                        <div class="<?php echo $class; ?>">
                            <h1 class="product-name"><?php echo $heading_title; ?></h1>
                            <?php if ($review_status) { ?>
                                <div class="rating product-comments">
                                    <p class="product-star">
                                        <?php for ($i = 1; $i <= 5; $i++) { ?>
                                            <?php if ($rating < $i) { ?>
                                                <span class="fa fa-stack"><i class="fa fa-star-o fa-stack-1x"></i></span>
                                            <?php } else { ?>
                                                <span class="fa fa-stack"><i class="fa fa-star fa-stack-1x"></i><i class="fa fa-star-o fa-stack-1x"></i></span>
                                            <?php } ?>
                                        <?php } ?>
                                    </p>
                                    <div class="comments-advices">
                                        <a href="" onclick="$('a[href=\'#tab-review\']').trigger('click'); return false;"><?php echo $translator->_('Based  on')?> <?php echo $reviews; ?></a>
                                        <a href="" onclick="$('a[href=\'#tab-review\']').trigger('click'); return false;"><i class="fa fa-pencil"></i> <?php echo $text_write; ?></a>
                                    </div>
                                </div>
                            <?php } ?>
                            <?php if ($price) { ?>
                                <ul class="product-price-group">
                                    <?php if (!$special) { ?>
                                        <li class="price"><?php echo $price; ?></li>
                                    <?php } else { ?>
                                        <li class="price"><?php echo $special; ?></li>
                                        <li class="old-price"><?php echo $price; ?></li>
                                        <li class="discount">
                                            <?php
                                                    $prspecial = $special;
                                                    $prspecial  = preg_replace( '/\D/', '', $prspecial);
                                                    $pr = $price;
                                                    $pr  = preg_replace( '/\D/', '', $pr);
                                                    $pecent = 100 - $prspecial / $pr * 100;
                                                    echo "-".round($pecent)."%";
                                            ?>
                                        </li>
                                    <?php } ?>
                                    <?php if ($points) { ?>
                                        <li><?php echo $text_points; ?> <?php echo $points; ?></li>
                                    <?php } ?>
                                    <?php if ($discounts) { ?>
                                        <li>
                                            <hr/>
                                        </li>
                                        <?php foreach ($discounts as $discount) { ?>
                                            <li><?php echo $discount['quantity']; ?><?php echo $text_discount; ?><?php echo $discount['price']; ?></li>
                                        <?php } ?>
                                    <?php } ?>
                                </ul>
                            <?php } ?>
                            <ul class="info-orther">
                                <?php if ($manufacturer) { ?>
                                    <li><?php echo $text_manufacturer; ?> <a href="<?php echo $manufacturers; ?>"><?php echo $manufacturer; ?></a></li>
                                <?php } ?>
                                <li style="width:100%;display: block;"><?php echo $text_model; ?> <?php echo $model; ?></li>
                                <?php if ($reward) { ?>
                                    <li><?php echo $text_reward; ?> <?php echo $reward; ?></li>
                                <?php } ?>
                                <li style="width:100%;display: block;"><?php echo $text_stock; ?> <?php echo $stock; ?></li>
                            </ul>

                            <div id="product_option" class="form-option">
                                <?php if ($options) { ?>
                                    <p class="form-option-title"><?php echo $text_option; ?></p>
                                    <?php foreach ($options as $option) { ?>
                                        <?php if ($option['type'] == 'select' && !in_array($option['option_id'], $option_id_color)) { ?>
                                            <div class="<?php echo ($option['required'] ? ' required' : ''); ?> attributes">
                                                <label class="attribute-label" for="input-option<?php echo $option['product_option_id']; ?>"><?php echo $option['name']; ?></label>
                                                <div class="attribute-list">
                                                    <select name="option[<?php echo $option['product_option_id']; ?>]" id="input-option<?php echo $option['product_option_id']; ?>">

                                                        <?php foreach ($option['product_option_value'] as $option_value) { ?>
                                                            <option value="<?php echo $option_value['product_option_value_id']; ?>"><?php echo $option_value['name']; ?>
                                                                <?php if ($option_value['price']) { ?>
                                                                    (<?php echo $option_value['price_prefix']; ?><?php echo $option_value['price']; ?>)
                                                                <?php } ?>
                                                            </option>
                                                        <?php } ?>
                                                    </select>
                                                </div>
                                            </div>
                                        <?php } ?>
                                        <?php if ($option['type'] == 'radio' && !in_array($option['option_id'], $option_id_color)) { ?>
                                            <div class="<?php echo ($option['required'] ? ' required' : ''); ?>">
                                                <label class="control-label"><?php echo $option['name']; ?></label>
                                                <div id="input-option<?php echo $option['product_option_id']; ?>">
                                                    <?php foreach ($option['product_option_value'] as $option_value) { ?>
                                                        <div class="radio">
                                                            <label>
                                                                <input type="radio" name="option[<?php echo $option['product_option_id']; ?>]" value="<?php echo $option_value['product_option_value_id']; ?>" />
                                                                <?php echo $option_value['name']; ?>
                                                                <?php if ($option_value['price']) { ?>
                                                                    (<?php echo $option_value['price_prefix']; ?><?php echo $option_value['price']; ?>)
                                                                <?php } ?>
                                                            </label>
                                                        </div>
                                                    <?php } ?>
                                                </div>
                                            </div>
                                        <?php } ?>
                                        <?php if ($option['type'] == 'checkbox' && !in_array($option['option_id'], $option_id_color)) { ?>
                                            <div class="<?php echo ($option['required'] ? ' required' : ''); ?>">
                                                <label class="control-label"><?php echo $option['name']; ?></label>
                                                <div id="input-option<?php echo $option['product_option_id']; ?>">
                                                    <?php foreach ($option['product_option_value'] as $option_value) { ?>
                                                        <div class="checkbox">
                                                            <label>
                                                                <input type="checkbox" name="option[<?php echo $option['product_option_id']; ?>][]" value="<?php echo $option_value['product_option_value_id']; ?>" />
                                                                <?php echo $option_value['name']; ?>
                                                                <?php if ($option_value['price']) { ?>
                                                                    (<?php echo $option_value['price_prefix']; ?><?php echo $option_value['price']; ?>)
                                                                <?php } ?>
                                                            </label>
                                                        </div>
                                                    <?php } ?>
                                                </div>
                                            </div>
                                        <?php } ?>
                                        <?php if ($option['type'] == 'image' && !in_array($option['option_id'], $option_id_color)) { ?>
                                            <div class="form-group<?php echo ($option['required'] ? ' required' : ''); ?>">
                                                <label class="control-label"><?php echo $option['name']; ?></label>
                                                <div id="input-option<?php echo $option['product_option_id']; ?>">
                                                    <?php foreach ($option['product_option_value'] as $option_value) { ?>
                                                        <div class="radio">
                                                            <label>
                                                                <input type="radio" name="option[<?php echo $option['product_option_id']; ?>]" value="<?php echo $option_value['product_option_value_id']; ?>" />
                                                                <img src="<?php echo $option_value['image']; ?>" alt="<?php echo $option_value['name'] . ($option_value['price'] ? ' ' . $option_value['price_prefix'] . $option_value['price'] : ''); ?>" class="img-thumbnail" /> <?php echo $option_value['name']; ?>
                                                                <?php if ($option_value['price']) { ?>
                                                                    (<?php echo $option_value['price_prefix']; ?><?php echo $option_value['price']; ?>)
                                                                <?php } ?>
                                                            </label>
                                                        </div>
                                                    <?php } ?>
                                                </div>
                                            </div>
                                        <?php } ?>
                                        <?php if ($option['type'] == 'text' && !in_array($option['option_id'], $option_id_color)) { ?>
                                            <div class="form-group<?php echo ($option['required'] ? ' required' : ''); ?>">
                                                <label class="control-label" for="input-option<?php echo $option['product_option_id']; ?>"><?php echo $option['name']; ?></label>
                                                <input type="text" name="option[<?php echo $option['product_option_id']; ?>]" value="<?php echo $option['value']; ?>" placeholder="<?php echo $option['name']; ?>" id="input-option<?php echo $option['product_option_id']; ?>" class="form-control" />
                                            </div>
                                        <?php } ?>
                                        <?php if ($option['type'] == 'textarea' && !in_array($option['option_id'], $option_id_color)) { ?>
                                            <div class="form-group<?php echo ($option['required'] ? ' required' : ''); ?>">
                                                <label class="control-label" for="input-option<?php echo $option['product_option_id']; ?>"><?php echo $option['name']; ?></label>
                                                <textarea name="option[<?php echo $option['product_option_id']; ?>]" rows="5" placeholder="<?php echo $option['name']; ?>" id="input-option<?php echo $option['product_option_id']; ?>" class="form-control"><?php echo $option['value']; ?></textarea>
                                            </div>
                                        <?php } ?>
                                        <?php if ($option['type'] == 'file') { ?>
                                            <div class="form-group<?php echo ($option['required'] ? ' required' : ''); ?>">
                                                <label class="control-label"><?php echo $option['name']; ?></label>
                                                <button type="button" id="button-upload<?php echo $option['product_option_id']; ?>" data-loading-text="<?php echo $text_loading; ?>" class="btn btn-default btn-block"><i class="fa fa-upload"></i> <?php echo $button_upload; ?></button>
                                                <input type="hidden" name="option[<?php echo $option['product_option_id']; ?>]" value="" id="input-option<?php echo $option['product_option_id']; ?>" />
                                            </div>
                                        <?php } ?>
                                        <?php if ($option['type'] == 'date') { ?>
                                            <div class="form-group<?php echo ($option['required'] ? ' required' : ''); ?>">
                                                <label class="control-label" for="input-option<?php echo $option['product_option_id']; ?>"><?php echo $option['name']; ?></label>
                                                <div class="input-group date">
                                                    <input type="text" name="option[<?php echo $option['product_option_id']; ?>]" value="<?php echo $option['value']; ?>" data-date-format="YYYY-MM-DD" id="input-option<?php echo $option['product_option_id']; ?>" class="form-control" />
                <span class="input-group-btn">
                <button class="btn btn-default" type="button"><i class="fa fa-calendar"></i></button>
                </span></div>
                                            </div>
                                        <?php } ?>
                                        <?php if ($option['type'] == 'datetime') { ?>
                                            <div class="form-group<?php echo ($option['required'] ? ' required' : ''); ?>">
                                                <label class="control-label" for="input-option<?php echo $option['product_option_id']; ?>"><?php echo $option['name']; ?></label>
                                                <div class="input-group datetime">
                                                    <input type="text" name="option[<?php echo $option['product_option_id']; ?>]" value="<?php echo $option['value']; ?>" data-date-format="YYYY-MM-DD HH:mm" id="input-option<?php echo $option['product_option_id']; ?>" class="form-control" />
                <span class="input-group-btn">
                <button type="button" class="btn btn-default"><i class="fa fa-calendar"></i></button>
                </span></div>
                                            </div>
                                        <?php } ?>
                                        <?php if ($option['type'] == 'time') { ?>
                                            <div class="form-group<?php echo ($option['required'] ? ' required' : ''); ?>">
                                                <label class="control-label" for="input-option<?php echo $option['product_option_id']; ?>"><?php echo $option['name']; ?></label>
                                                <div class="input-group time">
                                                    <input type="text" name="option[<?php echo $option['product_option_id']; ?>]" value="<?php echo $option['value']; ?>" data-date-format="HH:mm" id="input-option<?php echo $option['product_option_id']; ?>" class="form-control" />
                <span class="input-group-btn">
                <button type="button" class="btn btn-default"><i class="fa fa-calendar"></i></button>
                </span></div>
                                            </div>
                                        <?php } ?>
                                        <?php if (in_array($option['option_id'], $option_id_color)) { ?>
                                            <div class="<?php echo ($option['required'] ? ' required' : ''); ?> attributes">
                                                <label class="attribute-label" for="input-option<?php echo $option['product_option_id']; ?>"><?php echo $option['name']; ?></label>
                                                <div class="attribute-list product-option-color">
                                                    <select style="display: none" name="option[<?php echo $option['product_option_id']; ?>]" id="input-option<?php echo $option['product_option_id']; ?>">
                                                        <?php foreach ($option['product_option_value'] as $option_value) { ?>
                                                            <option value="<?php echo $option_value['product_option_value_id']; ?>"><?php echo $option_value['name']; ?>
                                                                <?php if ($option_value['price']) { ?>
                                                                    (<?php echo $option_value['price_prefix']; ?><?php echo $option_value['price']; ?>)
                                                                <?php } ?>
                                                            </option>
                                                        <?php } ?>
                                                    </select>

                                                    <ul class="list-color" data-product-option-id="<?php echo $option['product_option_id']?>">
                                                        <?php foreach ($option['product_option_value'] as $option_value) { ?>
                                                        <li data-product-option-value-id="<?php echo $option_value['product_option_value_id']; ?>" style="background: url('<?php echo $option_value['image'];?>');background-position-y: 23px;">
                                                            <a href="javascript:;"><?php echo $option_value['name']?></a>
                                                        </li>
                                                        <?php } ?>
                                                    </ul>
                                                </div>
                                            </div>
                                        <?php } ?>
                                    <?php } ?>
                                <?php } ?>
                                <?php if ($recurrings) { ?>
                                    <hr/>
                                    <h3><?php echo $text_payment_recurring ?></h3>
                                    <div class="form-group required">
                                        <select name="recurring_id" class="form-control">
                                            <option value=""><?php echo $text_select; ?></option>
                                            <?php foreach ($recurrings as $recurring) { ?>
                                                <option value="<?php echo $recurring['recurring_id'] ?>"><?php echo $recurring['name'] ?></option>
                                            <?php } ?>
                                        </select>
                                        <div class="help-block" id="recurring-description"></div>
                                    </div>
                                <?php } ?>
                                <div class="attributes">
                                    <label class="control-label attribute-label" for="input-quantity"><?php echo $entry_qty; ?></label>
                                    <div class="attribute-list product-qty">
                                        <div class="qty">
                                            <input type="text" name="quantity" value="<?php echo $minimum; ?>" size="2" id="input-quantity" />
                                            <input type="hidden" name="product_id" value="<?php echo $product_id; ?>" />

                                        </div>
                                        <div class="btn-plus">
                                            <a onclick="var result = document.getElementById('input-quantity');result.value++;" class="btn-plus-up">
                                                <i class="fa fa-caret-up"></i>
                                            </a>
                                            <a onclick="var result = document.getElementById('input-quantity'); var qty = result.value; if( !isNaN(qty) && qty > 1 ) result.value--;return false;" class="btn-plus-down">
                                                <i class="fa fa-caret-down"></i>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <?php if ($minimum > 1) { ?>
                                    <div class="alert alert-info"><i class="fa fa-info-circle"></i> <?php echo $text_minimum; ?></div>
                                <?php } ?>
                            </div>
                            <?php if($meta_description){ ?>
                            <div class="product-desc">
                                <?php echo $meta_description; ?>
                            </div>
                            <?php } ?>
                            <div class="form-action">
                                <div class="button-group">
                                    <button type="button" id="button-cart" data-loading-text="<?php echo $text_loading; ?>" class="btn-add-cart"><?php echo $button_cart; ?></button>
                                </div>
                                <div class="btn-group button-group">
                                    <a class="wishlist" title="<?php echo $button_wishlist; ?>" onclick="wishlist.add('<?php echo $product_id; ?>');">
                                        <i class="fa fa-heart-o"></i><br/><?php echo $translator->_('Wishlist')?>
                                    </a>
                                    <a class="compare" title="<?php echo $button_compare; ?>" onclick="compare.add('<?php echo $product_id; ?>');">
                                        <i class="fa fa-signal"></i><br/><?php echo $translator->_('Compare')?>
                                    </a>
                                </div>

                            </div>
                            <div class="form-share">
                                <div class="sendtofriend-print">
                                    <a href="javascript:print();"><i class="fa fa-print"></i> <?php echo $translator->_('Print')?></a>
                                </div>
                                <div class="network-share">
                                </div>
                            </div>
                            <div class="addthis_toolbox addthis_default_style"><a class="addthis_button_facebook_like" fb:like:layout="button_count"></a> <a class="addthis_button_tweet"></a> <a class="addthis_button_pinterest_pinit"></a> <a class="addthis_counter addthis_pill_style"></a></div>
                            <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-515eeaf54693130e"></script>
                        </div>
                    </div>
                    <div class="product-tab">
                        <ul class="nav nav-tab">
                            <li class="active"><a href="#tab-description" data-toggle="tab"><?php echo $tab_description; ?></a></li>
                            <?php if ($attribute_groups) { ?>
                                <li><a href="#tab-specification" data-toggle="tab"><?php echo $tab_attribute; ?></a></li>
                            <?php } ?>
                            <?php if ($review_status) { ?>
                                <li><a href="#tab-review" data-toggle="tab"><?php echo $tab_review; ?></a></li>
                            <?php } ?>
                        </ul>
                        <div class="tab-content tab-container">
                            <div class="tab-pane active" id="tab-description"><?php echo $description; ?></div>
                            <?php if ($attribute_groups) { ?>
                                <div class="tab-pane" id="tab-specification">
                                    <table class="table table-bordered">
                                        <?php foreach ($attribute_groups as $attribute_group) { ?>
                                            <tbody>
                                            <?php foreach ($attribute_group['attribute'] as $attribute) { ?>
                                                <tr>
                                                    <td width="200"><?php echo $attribute['name']; ?></td>
                                                    <td><?php echo $attribute['text']; ?></td>
                                                </tr>
                                            <?php } ?>
                                            </tbody>
                                        <?php } ?>
                                    </table>
                                </div>
                            <?php } ?>
                            <?php if ($review_status) { ?>
                                <div class="tab-pane tab-panel" id="tab-review">
                                    <form class="form-horizontal product-comments-block-tab">
                                        <div id="review"></div>
                                        <p><a class="btn-comment"><?php echo $text_write; ?></a></p>
                                        <?php if ($review_guest) { ?>
                                            <div class="form-group required">
                                                <div class="col-sm-12">
                                                    <label class="control-label" for="input-name"><?php echo $entry_name; ?></label>
                                                    <input type="text" name="name" value="" id="input-name" class="form-control" />
                                                </div>
                                            </div>
                                            <div class="form-group required">
                                                <div class="col-sm-12">
                                                    <label class="control-label" for="input-review"><?php echo $entry_review; ?></label>
                                                    <textarea name="text" rows="5" id="input-review" class="form-control"></textarea>
                                                    <div class="help-block"><?php echo $text_note; ?></div>
                                                </div>
                                            </div>
                                            <div class="form-group required">
                                                <div class="col-sm-12">
                                                    <label class="control-label"><?php echo $entry_rating; ?></label>
                                                    &nbsp;&nbsp;&nbsp; <?php echo $entry_bad; ?>&nbsp;
                                                    <input type="radio" name="rating" value="1" />
                                                    &nbsp;
                                                    <input type="radio" name="rating" value="2" />
                                                    &nbsp;
                                                    <input type="radio" name="rating" value="3" />
                                                    &nbsp;
                                                    <input type="radio" name="rating" value="4" />
                                                    &nbsp;
                                                    <input type="radio" name="rating" value="5" />
                                                    &nbsp;<?php echo $entry_good; ?></div>
                                            </div>
                                            <?php if(isset($captcha) && !empty($captcha)) {?>
                                                <?php echo $captcha;?>
                                            <?php } else if(isset($entry_captcha) && !empty($entry_captcha)){?>
                                                <div class="form-group required">
                                                    <div class="col-sm-12">
                                                        <label class="control-label" for="input-captcha"><?php echo $entry_captcha; ?></label>
                                                        <input type="text" name="captcha" value="" id="input-captcha" class="form-control" />
                                                    </div>
                                                </div>
                                            <?php }?>
                                            <div class="form-group">
                                                <div class="col-sm-12"> <img src="index.php?route=tool/captcha" alt="" id="captcha" /> </div>
                                            </div>
                                            <div class="buttons">
                                                <div class="pull-right">
                                                    <button type="button" id="button-review" data-loading-text="<?php echo $text_loading; ?>" class="btn btn-primary"><?php echo $button_continue; ?></button>
                                                </div>
                                            </div>
                                        <?php } else { ?>
                                            <?php echo $text_login; ?>
                                        <?php } ?>
                                    </form>
                                </div>
                            <?php } ?>
                        </div>
                    </div>
                </div>
                <?php if ($products) { ?>
                    <div class="page-product-box product-related-list">
                        <h3 class="heading"><?php echo $text_related; ?></h3>
                        <ul class="product-list owl-carousel" data-dots="false" data-loop="true" data-nav = "true" data-margin = "30" data-autoplayTimeout="1000" data-autoplayHoverPause = "true" data-responsive='{"0":{"items":1},"600":{"items":3},"1000":{"items":3}}'>
                            <?php $i = 0; ?>
                            <?php foreach ($products as $product) { ?>
                                <?php if ($column_left && $column_right) { ?>
                                    <?php $class = 'col-lg-6 col-md-6 col-sm-12 col-xs-12'; ?>
                                <?php } elseif ($column_left || $column_right) { ?>
                                    <?php $class = 'col-lg-4 col-md-4 col-sm-6 col-xs-12'; ?>
                                <?php } else { ?>
                                    <?php $class = 'col-lg-3 col-md-3 col-sm-6 col-xs-12'; ?>
                                <?php } ?>
                                <li>
                                    <div class="product-container">
                                        <div class="left-block">
                                            <a href="<?php echo $product['href']; ?>"><img src="<?php echo $product['thumb']; ?>" alt="<?php echo $product['name']; ?>" title="<?php echo $product['name']; ?>"/></a>
                                            <div class="quick-view">
                                                <a title="<?php echo $button_wishlist; ?>" class="heart" onclick="wishlist.add('<?php echo $product['product_id']; ?>');"></a>
                                                <a title="<?php echo $button_compare; ?>" class="compare" onclick="compare.add('<?php echo $product['product_id']; ?>');"></a>
                                                <a title="Quick view" class="search" href="#"></a>
                                            </div>
                                            <div class="add-to-cart">
                                                <a title="<?php echo $button_cart; ?>" onclick="cart.add('<?php echo $product['product_id']; ?>');"><?php echo $button_cart; ?></a>
                                            </div>
                                        </div>
                                        <div class="right-block">
                                            <h5 class="product-name"><a href="<?php echo $product['href']; ?>"><?php echo $product['name']; ?></a></h5>
                                            <?php if ($product['rating']) { ?>
                                                <p class="product-star">
                                                    <?php for ($i = 1; $i <= 5; $i++) { ?>
                                                        <?php if ($product['rating'] < $i) { ?>
                                                            <span class="fa fa-stack"><i class="fa fa-star-o fa-stack-1x"></i></span>
                                                        <?php } else { ?>
                                                            <span class="fa fa-stack"><i class="fa fa-star fa-stack-1x"></i><i class="fa fa-star-o fa-stack-1x"></i></span>
                                                        <?php } ?>
                                                    <?php } ?>
                                                </p>
                                            <?php } ?>
                                            <?php if ($product['price']) { ?>
                                                <div class="content_price">
                                                    <?php if (!$product['special']) { ?>
                                                        <span class="price product-price"><?php echo $product['price']; ?></span>
                                                    <?php } else { ?>
                                                        <span class="price product-price"><?php echo $product['special']; ?></span> <span class="price old-price"><?php echo $product['price']; ?></span>
                                                    <?php } ?>
                                                </div>
                                            <?php } ?>
                                        </div>
                                    </div>
                                </li>

                            <?php } ?>
                        </ul>
                    </div>
                <?php } ?>

                <?php echo $content_bottom; ?></div>
            <?php echo $column_right; ?></div>

    </div>
    <script type="text/javascript"><!--
        $('select[name=\'recurring_id\'], input[name="quantity"]').change(function(){
            $.ajax({
                url: 'index.php?route=product/product/getRecurringDescription',
                type: 'post',
                data: $('input[name=\'product_id\'], input[name=\'quantity\'], select[name=\'recurring_id\']'),
                dataType: 'json',
                beforeSend: function() {
                    $('#recurring-description').html('');
                },
                success: function(json) {
                    $('.alert, .text-danger').remove();

                    if (json['success']) {
                        $('#recurring-description').html(json['success']);
                    }
                }
            });
        });
        //--></script>
    <script type="text/javascript"><!--
        $('#button-cart').on('click', function() {
            $.ajax({
                url: 'index.php?route=checkout/cart/add',
                type: 'post',
                data: $('#product input[type=\'text\'], #product input[type=\'hidden\'], #product input[type=\'radio\']:checked, #product input[type=\'checkbox\']:checked, #product select, #product textarea'),
                dataType: 'json',
                beforeSend: function() {
                    $('#button-cart').bootstrapBtn('loading');
                },
                complete: function() {
                    $('#button-cart').bootstrapBtn('reset');
                },
                success: function(json) {
                    $('.alert, .text-danger').remove();
                    $('.form-group').removeClass('has-error');

                    if (json['error']) {
                        if (json['error']['option']) {
                            for (i in json['error']['option']) {
                                var element = $('#input-option' + i.replace('_', '-'));

                                if (element.parent().hasClass('input-group')) {
                                    element.parent().after('<div class="text-danger">' + json['error']['option'][i] + '</div>');
                                } else {
                                    element.after('<div class="text-danger">' + json['error']['option'][i] + '</div>');
                                }
                            }
                        }

                        if (json['error']['recurring']) {
                            $('select[name=\'recurring_id\']').after('<div class="text-danger">' + json['error']['recurring'] + '</div>');
                        }

                        // Highlight any found errors
                        $('.text-danger').parent().addClass('has-error');
                    }

                    if (json['success']) {
                        $('.breadcrumb').after('<div class="alert alert-success">' + json['success'] + '<button type="button" class="close" data-dismiss="alert">&times;</button></div>');

                        $('#cart-total').html(json['total']);

                        $('html, body').animate({ scrollTop: 0 }, 'slow');

                        $('.cart-block').load('index.php?route=common/cart/info .cart-block .cart-block-content');
                    }
                }
            });
        });
        //--></script>
    <script type="text/javascript"><!--
        $('.date').datetimepicker({
            pickTime: false
        });

        $('.datetime').datetimepicker({
            pickDate: true,
            pickTime: true
        });

        $('.time').datetimepicker({
            pickDate: false
        });

        $('button[id^=\'button-upload\']').on('click', function() {
            var node = this;

            $('#form-upload').remove();

            $('body').prepend('<form enctype="multipart/form-data" id="form-upload" style="display: none;"><input type="file" name="file" /></form>');

            $('#form-upload input[name=\'file\']').trigger('click');

            timer = setInterval(function() {
                if ($('#form-upload input[name=\'file\']').val() != '') {
                    clearInterval(timer);

                    $.ajax({
                        url: 'index.php?route=tool/upload',
                        type: 'post',
                        dataType: 'json',
                        data: new FormData($('#form-upload')[0]),
                        cache: false,
                        contentType: false,
                        processData: false,
                        beforeSend: function() {
                            $(node).bootstrapBtn('loading');
                        },
                        complete: function() {
                            $(node).bootstrapBtn('reset');
                        },
                        success: function(json) {
                            $('.text-danger').remove();

                            if (json['error']) {
                                $(node).parent().find('input').after('<div class="text-danger">' + json['error'] + '</div>');
                            }

                            if (json['success']) {
                                alert(json['success']);

                                $(node).parent().find('input').attr('value', json['code']);
                            }
                        },
                        error: function(xhr, ajaxOptions, thrownError) {
                            alert(thrownError + "\r\n" + xhr.statusText + "\r\n" + xhr.responseText);
                        }
                    });
                }
            }, 500);
        });
        //--></script>
    <script type="text/javascript"><!--
        $('#review').delegate('.pagination a', 'click', function(e) {
            e.preventDefault();

            $('#review').fadeOut('slow');

            $('#review').load(this.href);

            $('#review').fadeIn('slow');
        });

        $('#review').load('index.php?route=product/product/review&product_id=<?php echo $product_id; ?>');

        $('#button-review').on('click', function() {
            $.ajax({
                url: 'index.php?route=product/product/write&product_id=<?php echo $product_id; ?>',
                type: 'post',
                dataType: 'json',
                data: 'name=' + encodeURIComponent($('input[name=\'name\']').val()) + '&text=' + encodeURIComponent($('textarea[name=\'text\']').val()) + '&rating=' + encodeURIComponent($('input[name=\'rating\']:checked').val() ? $('input[name=\'rating\']:checked').val() : '') + '&captcha=' + encodeURIComponent($('input[name=\'captcha\']').val()),
                beforeSend: function() {
                    $('#button-review').bootstrapBtn('loading');
                },
                complete: function() {
                    $('#button-review').bootstrapBtn('reset');
                    $('#captcha').attr('src', 'index.php?route=tool/captcha#'+new Date().getTime());
                    $('input[name=\'captcha\']').val('');
                },
                success: function(json) {
                    $('.alert-success, .alert-danger').remove();

                    if (json['error']) {
                        $('#review').after('<div class="alert alert-danger"><i class="fa fa-exclamation-circle"></i> ' + json['error'] + '</div>');
                    }

                    if (json['success']) {
                        $('#review').after('<div class="alert alert-success"><i class="fa fa-check-circle"></i> ' + json['success'] + '</div>');

                        $('input[name=\'name\']').val('');
                        $('textarea[name=\'text\']').val('');
                        $('input[name=\'rating\']:checked').prop('checked', false);
                        $('input[name=\'captcha\']').val('');
                    }
                }
            });
        });

        //--></script>

<?php echo $footer; ?>
