<div class="x_content">
    <div class="form-group">
        <label class="control-label col-md-3">Turn on cached</label>
        <div class="col-md-1">
            <label class="">
                <input type="checkbox" class="js-switch" value="1" name="ocivity3_kuteshop_theme[cached]" <?php echo (isset($enable_cached) && $enable_cached ? 'checked="checked"' : '')?>/>
            </label>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-md-3">Use layout</label>
        <div class="col-md-5">
            <select name="ocivity3_kuteshop_theme[layout_id]" class="form-control">
                <?php foreach($layouts as $layout_id => $layout_name) { ?>
                    <option value="<?php echo $layout_id?>" <?php echo ($current_layout_id == $layout_id ? 'selected="selected"' : '')?>><?php echo $layout_name?></option>
                <?php } ?>
            </select>
        </div>
    </div>
    <div class="clearfix"></div>
</div>

<script type="text/javascript">
    $(document).ready(function(){
    });
</script>