<ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
    <li role="presentation" class="active"><a href="#tab_translation_global" id="home-tab" role="tab" data-toggle="tab" aria-expanded="true">Global</a></li>
    <li role="presentation" class=""><a href="#tab_translation_files" role="tab" id="keywords-tab2" data-toggle="tab" aria-expanded="false">Files</a></li>
</ul>
<div id="myTabTranslationContent" class="tab-content">
    <div role="tabpanel" class="tab-pane fade active in" id="tab_translation_global" aria-labelledby="global-translation-tab">
        <div class="col-md-12">
            <div class="row">
                <div class="form-group">
                    <div class="col-md-10 warning_perrmission_translation" style="display: none;">
                        <span class="label label-danger">This file can not writeable. Please CHMOD all files&folders in ocivity3/app/i18n/ 777 to continue use feature translate.</span>
                    </div>
                    <div class="col-md-8 msg_save_translation" style="display: none;">
                        <span class="label label-success">Save translate is completed.</span>
                    </div>
                    <div class="col-md-4 pull-right btn-translation" style="margin: 0 -5px 0;display: block;">
                        <button type="button" class="btn btn btn-primary pull-right save-translation">Save translate</button>
                        <button type="button" class="btn btn btn-success pull-right" data-toggle="modal" data-target=".bs-example-modal-sm">+</button>
                    </div>
                </div>
            </div>
            <div class="row fields">
                <?php if(!isset($permission_message)) { ?>
                <input type="hidden" name="file_global_translation" value="<?php echo $global_file?>">
                <?php foreach($global_language as $key => $value) {?>
                    <div class="form-group">
                        <div class="col-md-3">
                            <input type="text" class="form-control" name="global_translation[<?php echo md5(base64_encode(trim($key)))?>][key]" value="<?php echo trim($key)?>" readonly>
                        </div>

                        <div class="col-md-8">
                            <input type="text" class="form-control" name="global_translation[<?php echo md5(base64_encode(trim($key)))?>][value]" value="<?php echo trim($value)?>">
                        </div>
                        <div class="col-md-1">
                            <span class="fa fa-close remove" style="font-size: 28px;color: red;cursor: pointer"></span>
                        </div>
                        <div class="clearfix" style="margin-top:6px"></div><br>
                    </div>
                <?php } ?>
                <?php }else{ ?>
                    <span style="color: red;text-align: center;display: block;font-size: 14px;"><?php echo $permission_message?></span>
                <?php } ?>
            </div>
        </div>
    </div>
    <div role="tabpanel" class="tab-pane fade in" id="tab_translation_files" aria-labelledby="files-translation-tab">
        <div class="col-md-12">
            <div class="col-md-2">
                <div id="container_id"></div>
            </div>
            <div class="col-md-10">
                <input type="hidden" name="file_translation">
                <div class="col-md-12">
                    <div class="form-group">
                        <div class="col-md-10 warning_perrmission_translation" style="display: none;">
                            <span class="label label-danger">This file can not writeable. Please CHMOD all files&folders in catalog/language 777 to continue use feature translate.</span>
                        </div>
                        <div class="col-md-10 msg_save_translation" style="display: none;">
                            <span class="label label-success">Save translate is completed.</span>
                        </div>
                        <div class="col-md-2 pull-right btn-translation" style="margin: 0 -14px 0;display: none;">
                            <button type="button" class="btn btn btn-primary pull-right save-translation">Save translate</button>
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    <p><span class="path_file_translation"></span></p>
                </div>
                <div class="container_translating">
                    Please select file from left panel to translate
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/x-jquery-tmpl" id="item_translation">
<div class="form-group">
    <div class="col-md-3">
        <input type="text" class="form-control" name="translation[${key}][key]" value="${key}" readonly>
    </div>

    <div class="col-md-9">
        <input type="text" class="form-control" name="translation[${key}][value]" value="${value}">
    </div>

    <div class="clearfix" style="margin-top:6px"></div><br>
</div>
</script>
<script type="text/x-jquery-tmpl" id="item_global_translation">
<div class="form-group">
    <div class="col-md-3">
        <input type="text" class="form-control" name="global_translation[${key}][key]" value="${value}" readonly>
    </div>

    <div class="col-md-8">
        <input type="text" class="form-control" name="global_translation[${key}][value]" value="">
    </div>

    <div class="col-md-1">
        <span class="fa fa-close remove" style="font-size: 28px;color: red;cursor: pointer"></span>
    </div>

    <div class="clearfix" style="margin-top:6px"></div><br>
</div>
</script>
<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-body">
                <div class="form-group">
                    <div class="col-md-12">
                        <label for="" class="control-label col-md-2">Title</label>
                        <div class="col-md-10">
                            <input type="text" class="form-control" name="global_title">
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-success add-translation">Add</button>
            </div>

        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready( function() {
        var container_files_tab  = $("#tab_translation_files");
        var container_global_tab = $("#tab_translation_global");
        var container_modal      = $(".modal");

        $('#container_id').fileTree({
            root: '<?php echo $locale_language?>',
            script: 'index.php?route=module/kuteshop_setting_v2/_list_folder&token=<?php echo $token?>'
        }, function(file) {
            $(".btn-translation").hide();

            $(".path_file_translation").html("<strong>Reading file</strong>: "+ file);
            $.ajax({
                type: 'POST',
                url: 'index.php?route=module/kuteshop_setting_v2/_read_translate_file&token=<?php echo $token?>',
                data: 'file='+file,
                dataType: 'json',
                success: function(data){
                    var html = "";
                    $.each(data._, function(k, v){
                        html += $( "#item_translation" ).tmpl( {key: k, value: v}).html();
                    });

                    $(".btn-translation").show();

                    $("input[name=file_translation]").val(file);
                    $(".container_translating").html(html);

                    if(!data.is_writeable){
                        $(".btn-translation").find("button").attr('disabled', true);
                        $(".warning_perrmission_translation").show();
                        $(".container_translating").find("input").attr('disabled', true);
                    }else{
                        $(".warning_perrmission_translation").hide();
                        $(".btn-translation").find("button").removeAttr('disabled');
                    }
                }
            });
        });

        container_global_tab.find(".save-translation").on("click", function(){
            var file = container_global_tab.find("input[name=file_global_translation]").val();
            var data = $("form[name=form-setting]").find("#tab_translation_global").find("input[name*=global_translation]").serialize();

            container_global_tab.find(".msg_save_translation").hide();
            container_global_tab.find(".warning_perrmission_translation").hide();

            $.ajax({
                type: "POST",
                url: 'index.php?route=module/kuteshop_setting_v2/_save_translate_global_file&token=<?php echo $token?>',
                data: 'file='+file+'&'+data,
                dataType: 'json',
                success: function(data){
                    if(!data.error){
                        container_global_tab.find(".msg_save_translation").show();
                        setTimeout(function(){
                            container_global_tab.find(".msg_save_translation").fadeOut();
                        }, 5000);
                    }else{
                        container_global_tab.find(".warning_perrmission_translation").show();
                        setTimeout(function(){
                            container_global_tab.find(".warning_perrmission_translation").fadeOut();
                        }, 5000);
                    }
                }
            });
        });

        container_modal.find(".add-translation").on("click", function(){
            var key = container_modal.find("input[name=global_title]").val();

            if(!key){
                return true;
            }
            var html = $( "#item_global_translation" ).tmpl({key: $.md5(key), value: key});
            container_global_tab.find(".row.fields").prepend(html.prop('outerHTML'));
            $(".bs-example-modal-sm").modal('hide');
        });

        container_global_tab.delegate('.fa.fa-close.remove','click', function(){
            var self = $(this);
            self.closest('.form-group').remove();
        });

        container_files_tab.find(".save-translation").on("click", function(){
            var file = container_files_tab.find("input[name=file_translation]").val();
            var data = $("form[name=form-setting]").find("#tab_translation_files").find("input[name*=translation]").serialize();

            container_files_tab.find(".msg_save_translation").hide();

            $.ajax({
                type: "POST",
                url: 'index.php?route=module/kuteshop_setting_v2/_save_translate_file&token=<?php echo $token?>',
                data: 'file='+file+'&data='+data,
                dataType: 'json',
                success: function(data){
                    if(!data.error){
                        container_files_tab.find(".msg_save_translation").show();

                        setTimeout(function(){
                            container_files_tab.find(".msg_save_translation").fadeOut();
                        }, 3000);
                    }
                }
            });

        });
    });
</script>
