<div id="address-box">
    <a href="#"><img src="image/catalog/introduce-logo.png" alt="" /></a>
    <div id="address-list">
        <div class="tit-name"><?php echo $translator->_('Address:')?></div>
        <div class="tit-contain"><?php echo $translator->_('Example Street 68, Mahattan, New York, USA.')?></div>
        <div class="tit-name"><?php echo $translator->_('Phone:')?></div>
        <div class="tit-contain">+00 123 456 789</div>
        <div class="tit-name"><?php echo $translator->_('Email:')?></div>
        <div class="tit-contain">support@business.com</div>
    </div>
</div> 
        