
        <div class="col-sm-12">
            <ul class="footer-menu-list">
                <li><a href="#" ><?php echo $translator->_('Company Info - Partnerships')?></a></li>
            </ul>
        </div>
        <div class="col-sm-12">
            <ul class="footer-menu-list">
                <li><a href="#" ><?php echo $translator->_('Online Shopping')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Promotions')?></a></li>
                <li><a href="#" ><?php echo $translator->_('My Orders')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Help')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Site Map')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Customer Service')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Support')?></a></li>
            </ul>
        </div>
        <div class="col-sm-12">
            <ul class="footer-menu-list">
                <li><a href="#" ><?php echo $translator->_('Most Populars')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Best Sellers')?></a></li>
                <li><a href="#" ><?php echo $translator->_('New Arrivals')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Special Products')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Manufacturers')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Our Stores')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Shipping')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Payments')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Warantee')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Refunds')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Checkout')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Discount')?></a></li>
            </ul>
        </div>
        <div class="col-sm-12">
            <ul class="footer-menu-list">
                <li><a href="#" ><?php echo $translator->_('Terms & Conditions')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Policy')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Shipping')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Payments')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Returns')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Refunds')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Warrantee')?></a></li>
                <li><a href="#" ><?php echo $translator->_('FAQ')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Contact')?></a></li>
            </ul>
        </div>
        
    