 <!-- #trademark-text-box -->
    <div id="trademark-text-box" class="row">
        <div class="col-sm-12">
            <ul id="trademark-search-list" class="trademark-list">
                <li class="trademark-text-tit"><?php echo $translator->_('HOT SEARCHED KEYWORDS:')?></li>
                <li><a href="#" ><?php echo $translator->_('Xiaomio Mi3')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Digiflipo Pro XT 712 Tablet')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Mi 3 Phones')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Iphoneo 6 Plus')?></a></li>
                <li><a href="#" ><?php echo $translator->_("Women's Messenger Bags")?></a></li>
                <li><a href="#" ><?php echo $translator->_('Wallets')?></a></li>
                <li><a href="#" ><?php echo $translator->_("'Women's Clutches'")?></a></li>
                <li><a href="#" ><?php echo $translator->_('Backpacks Totes')?></a></li>
            </ul>
        </div>
        <div class="col-sm-12">
            <ul id="trademark-tv-list" class="trademark-list">
                <li class="trademark-text-tit"><?php echo $translator->_('TVS:')?></li>
                <li><a href="#" ><?php echo $translator->_('Sonyo TV')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Samsing TV')?></a></li>
                <li><a href="#" ><?php echo $translator->_('LGG TV')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Onidai TV')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Toshibao TV')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Philipsi TV')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Micromaxo TV')?></a></li>
                <li><a href="#" ><?php echo $translator->_('LED TV')?></a></li>
                <li><a href="#" ><?php echo $translator->_('LCD TV')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Plasma TV')?></a></li>
                <li><a href="#" ><?php echo $translator->_('3D TV')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Smart TV')?></a></li>
            </ul>
        </div>
        <div class="col-sm-12">
            <ul id="trademark-mobile-list" class="trademark-list">
                <li class="trademark-text-tit"><?php echo $translator->_('MOBILES:')?></li>
                <li><a href="#" ><?php echo $translator->_('Moto E')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Samsing Mobile')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Micromaxi Mobile')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Nokian Mobile')?></a></li>
                <li><a href="#" ><?php echo $translator->_('HTCi Mobile')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Sonyo Mobile')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Appleo Mobile')?></a></li>
                <li><a href="#" ><?php echo $translator->_('LGG Mobile')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Karbonni Mobile')?></a></li>
            </ul>
        </div>
        <div class="col-sm-12">
            <ul id="trademark-laptop-list" class="trademark-list">
                <li class="trademark-text-tit"><?php echo $translator->_('LAPTOPS::')?></li>
                <li><a href="#" ><?php echo $translator->_('Appleo Laptop')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Acer Laptop')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Samsing Laptop')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Lenov Laptop')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Sonyo Laptop')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Delli Laptop')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Asuso Laptop')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Toshibao Laptop')?></a></li>
                <li><a href="#" ><?php echo $translator->_('LGG Laptop')?></a></li>
                <li><a href="#" ><?php echo $translator->_('HPo Laptop')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Notebook')?></a></li>
            </ul>
        </div>
        <div class="col-sm-12">
            <ul id="trademark-watches-list" class="trademark-list">
                <li class="trademark-text-tit"><?php echo $translator->_('WATCHES:')?></li>
                <li><a href="#" ><?php echo $translator->_('FCUKo Watches')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Titan Watches')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Casioo Watches')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Fastrack Watches')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Timexi Watches')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Fossili Watches')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Dieselo Watches')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Toshibao Laptop')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Luxury Watches')?></a></li>
            </ul>
        </div>
        <div class="col-sm-12">
            <ul id="trademark-shoes-list" class="trademark-list">
                <li class="trademark-text-tit"><?php echo $translator->_('FOOTWEAR:')?></li>
                <li><a href="#" ><?php echo $translator->_('Shoes')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Casual Shoes')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Sports Shoes')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Adidasi Shoes')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Gas Shoes')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Pumai Shoes')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Reeboki Shoes')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Woodlandi Shoes')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Red tape Shoes')?></a></li>
                <li><a href="#" ><?php echo $translator->_('Nikeo Shoes')?></a></li>
            </ul>
        </div>
    </div><!-- /#trademark-text-box -->