<style>
    body.kuteshop .btn{
        background: <?php echo $general_color;?>!important;
        border-color: <?php echo $general_color;?>!important;
    }

    .option5 #main-menu .navbar .navbar-nav>li:hover, .option5 #main-menu .navbar .navbar-nav>li.active,
    .option2 #main-menu .navbar .navbar-nav>li:hover, .option2 #main-menu .navbar .navbar-nav>li.active{
        background: <?php echo Ocart::adjustColor($general_color, 400);?> !important;
    }
    .option2 .box-vertical-megamenus .title{
        background: <?php echo Ocart::adjustColor($general_color, 288);?> !important;
    }
    #main-menu .navbar .navbar-nav>li:hover, #main-menu .navbar .navbar-nav>li.active{
        background: <?php echo $general_color;?>!important;
    }
    .box-vertical-megamenus .vertical-menu-content{
        border-top:3px solid <?php echo $general_color;?>!important;
    }
    .header-top-right{
        border-top:3px solid <?php echo $general_color;?>!important;
    }
    /* ======================================================== Header ===============================================*/

    body.kuteshop .box-vertical-megamenus .vertical-menu-list>li:hover {
        background: <?php echo $general_color;?> !important;
    }

    .button:hover{
        background: <?php echo $general_color;?> !important;;
        border: 1px solid <?php echo $general_color;?> !important;;
    }
    .top-banner h1{
        color: <?php echo $general_color;?> !important;;
    }
    #user-info-opntop .dropdown-menu{
        border-top: 2px solid <?php echo $general_color;?> !important;;
    }
    .top-header .dropdown-menu{
        border-top: 2px solid <?php echo $general_color;?> !important;;
    }
    .main-header .header-search-box .form-inline .btn-search{
        background: <?php echo $general_color;?> url("catalog/view/theme/kute/images/search.png") no-repeat center center;
    }

    .main-header .shopping-cart-box a.cart-link:after{
        background: <?php echo $general_color;?> url('catalog/view/theme/kute/images/cart.png') no-repeat center center;
    }
    .cart-block .cart-block-content  .product-info .p-right .p-rice{
        color: <?php echo $general_color;?> !important;;
    }
    .cart-block .cart-block-content .cart-buttons a.btn-check-out{
        background:<?php echo $general_color;?> !important;;
    }

    .box-vertical-megamenus .all-category span:hover{
        background: <?php echo $general_color;?> !important;;
        border-color: <?php echo $general_color;?> !important;;
    }
    .vertical-dropdown-menu .mega-group-header span{
        border-bottom: 1px solid <?php echo $general_color;?> !important;;
    }
    .vertical-dropdown-menu .mega-products .mega-product .product-price .new-price{
        color: <?php echo $general_color;?>;
    }
    #main-menu .dropdown-menu .block-container .group_header>a{
        border-bottom: 1px solid <?php echo $general_color;?> !important;;
    }
    .nav-menu-default{
        background: <?php echo $general_color;?> !important;;
    }
    /* ======================================================== Main ===============================================*/
    .product-list li .add-to-cart:hover {
        background: <?php echo $general_color;?> !important;;
    }
    .nav-menu-default ul>li>a:hover,
    .nav-menu-default ul>li.active>a,
    .nav-menu-default ul>li.selected>a{
        background: <?php echo $general_color;?> !important;;
    }
    .nav-menu-red li a:hover,
    .nav-menu-red li.active a,
    .nav-menu-red li.selected a{
        background: <?php echo $general_color;?> !important;;
    }

    .header-top-right .homeslider .bx-controls-direction .bx-prev,
    .header-top-right .homeslider .bx-controls-direction .bx-next{
        background: <?php echo $general_color;?> !important;;
    }
    .header-top-right .homeslider .bx-wrapper .bx-pager.bx-default-pager a:hover, .header-top-right .homeslider .bx-wrapper .bx-pager.bx-default-pager a.active {
        background: <?php echo $general_color;?> !important;;
    }
    .latest-deals .latest-deal-content{
        border: 3px solid <?php echo $general_color;?> !important;;
    }
    .popular-tabs .nav-tab li:hover,.popular-tabs .nav-tab li.active{
        border-bottom: 3px solid <?php echo $general_color;?> !important;;
    }
    .product-list li .quick-view a:hover{
        background-color: <?php echo $general_color;?>  !important;;
    }
    .product-list li .product-price{
        color: <?php echo $general_color;?> !important;;
    }
    .owl-controls .owl-prev:hover,
    .owl-controls .owl-next:hover{
        background: <?php echo $general_color;?> !important;;
    }
    .brand-showcase .brand-showcase-title{
        border-bottom: 3px solid <?php echo $general_color;?> !important;;
    }
    .trademark-product .info-product .btn-view-more:hover{
        background: <?php echo $general_color;?> !important;;
    }
    .trademark-product .info-product .quick-view a:hover{
        background: <?php echo $general_color;?> !important;;
    }
    .group-title span {
        border-bottom: 3px solid <?php echo $general_color;?> !important;;
    }
    .cate-box .cate-link:hover {
        background: <?php echo $general_color;?> !important;
    }
    #mail-box .btn {
        background: <?php echo $general_color;?> !important;;
    }
    .tree-menu li:hover>a,
    .tree-menu li.active>a,
    .tree-menu li:hover>span:before,
    .tree-menu li.active>span:before
    {
        color: <?php echo $general_color;?> !important;;
    }
    .layered-filter-price .slider-range-price{
        background: <?php echo $general_color;?> !important;;
    }
    .check-box-list label:hover{
        color: <?php echo $general_color;?> !important;;
    }
    .check-box-list input[type="checkbox"]:checked + label span.button{
        background: <?php echo $general_color;?> url("catalog/view/theme/kute/images/checked.png") no-repeat center center !important;;
    }
    .check-box-list input[type="checkbox"]:checked + label{
        color: <?php echo $general_color;?> !important;;
    }
    .filter-color li input[type="checkbox"]:checked + label{
        border-color: <?php echo $general_color;?> !important;;
    }
    .owl-controls .owl-dots .owl-dot.active{
        background: <?php echo $general_color;?> !important;;
    }
    .products-block .product-price{
        color: <?php echo $general_color;?> !important;;
    }
    .products-block .link-all{
        border: 1px solid <?php echo $general_color;?> !important;;
        background: <?php echo $general_color;?> !important;;
    }
    .category-slider .owl-controls .owl-prev:hover,
    .category-slider .owl-controls .owl-next:hover{
        background: <?php echo $general_color;?> !important;;
    }
    .sortPagiBar .bottom-pagination .pagination > li.active > span{
        background-color: <?php echo $general_color;?> !important;;
        border-color: <?php echo $general_color;?> !important;;
    }
    .page-heading span.page-heading-title{
        border-bottom: 3px solid <?php echo $general_color;?> !important;;
    }
    .display-product-option li.selected span,
    .display-product-option li:hover span
    {
        background-color: <?php echo $general_color;?> !important;;
    }
    .product-list.list .add-to-cart{
        background: <?php echo $general_color;?> !important;;
    }
    .product-list.style2.grid .add-to-cart a{
        background: <?php echo $general_color;?> !important;;
    }
    .sortPagiBar .bottom-pagination .pagination a:hover{
        background: <?php echo $general_color;?> !important;;
    }
    .sortPagiBar .bottom-pagination .pagination .active a{
        background: <?php echo $general_color;?> !important;;
    }
    .page-order ul.step li.current-step{
        border-bottom: 3px solid <?php echo $general_color;?> !important;;
    }
    .page-order .cart_navigation a.next-btn{
        background: <?php echo $general_color;?> !important;;
        border: 1px solid <?php echo $general_color;?> !important;;
    }
    .page-order .cart_navigation a:hover{
        background: <?php echo $general_color;?> !important;;
    }
    .cart_summary .qty a:hover{
        background: <?php echo $general_color;?> !important;;
    }
    #product .pb-right-column .product-price-group .price{
        color: <?php echo $general_color;?> !important;;
    }
    #product .pb-right-column .form-option #size_chart{
        color: <?php echo $general_color;?> !important;;
    }
    #product .pb-right-column .form-option .list-color li:hover,
    #product .pb-right-column .form-option .list-color li.active{
        border: 1px solid <?php echo $general_color;?> !important;;
    }
    #product .pb-right-column .form-action .button-group .wishlist:hover .fa,
    #product .pb-right-column .form-action .button-group .compare:hover .fa{
        background: <?php echo $general_color;?> !important;;
    }
    .blog-posts .post-item .entry-more a:hover{
        background: <?php echo $general_color;?> !important;;
    }
    .coment-form .btn-comment:hover{
        background: <?php echo $general_color;?> !important;;
        border:1px solid <?php echo $general_color;?> !important;;
    }
    .btn-primary:hover{
        background: <?php echo $general_color;?> !important;;
        border: 1px solid <?php echo $general_color;?> !important;;
    }
    .table-compare .price{
        color: <?php echo $general_color;?> !important;;
    }
    .table-compare .add-cart{
        background: <?php echo $general_color;?> !important;;
    }
    .today-deals .deals-product-list .product-info .show-count-down .box-count{
        color: <?php echo $general_color;?> !important;;
    }
    .today-deals .deals-product-list .product-info .product-meta .price{
        color: <?php echo $general_color;?> !important;;
    }
    .trademark-product .info-product .product-price{
        color: <?php echo $general_color;?> !important;;
    }
    .scroll_top:hover{
        background: <?php echo $general_color;?> !important;;
    }
    .btn-add-cart{
        background: <?php echo $general_color;?> !important;;
    }
    #contact #btn-send-contact:hover{
        background: <?php echo $general_color;?> !important;;
    }
    /*<!--  TURN OFF -->*/
    .option5 .header-top-right{
        border-top: 0 !important;
    }
</style>