<!-- Home slideder-->
<div class="homeslide8">
    <ul class="bxslider-background home-slider8">
        <li class="item" style="background-image: url('catalog/view/theme/kute/images/data/option8/slider1.jpg');">
            <div class="content">
                <h3 class="title caption">Paris fashion week</h3>
                <h2 class="sub-title caption">fashion talents from paris </h2>
                <p class="desc caption">Quisque malesuada placerat nisl. Quisque libero metus, condimentum nec, tempor a, commodo mollis, magna. 
                Vestibulum turpis sem, aliquet eget, lobortis pellentesque, rutrum eu, nisl. Maecena</p>
                <a href="#" class="sdide-button caption">Shop now</a>
            </div>
        </li>
        <li class="item" style="background-image: url('catalog/view/theme/kute/images/data/option8/slider2.jpg');">
            <div class="content">
                <h3 class="title caption">Paris fashion week</h3>
                <h2 class="sub-title caption">fashion talents from paris </h2>
                <p class="desc caption">Quisque malesuada placerat nisl. Quisque libero metus, condimentum nec, tempor a, commodo mollis, magna. 
                Vestibulum turpis sem, aliquet eget, lobortis pellentesque, rutrum eu, nisl. Maecena</p>
                <a href="#" class="sdide-button caption">Shop now</a>
            </div>
        </li>
    </ul>
</div>
<!-- Top banner -->
<div class="block-banner8">
    <div class="container">
        <div class="row">
            <div class="item col-sm-4">
                <div class="banner-opacity"><a href="#"><img src="catalog/view/theme/kute/images/data/option8/b1.jpg" alt="Banner"></a></div>
            </div>
            <div class="item col-sm-4">
                <div class="banner-boder-zoom2 banner-text">
                    <a href="#"><img src="catalog/view/theme/kute/images/data/option8/b2.jpg" alt="Banner"></a>
                    <div class="banner-content">
                        <h2 class="banner-title">FOR WOMEN</h2>
                        <div class="banner-desc">Deals Shop Always Open</div>
                        <a href="#" class="banner-button">Shop now</a>
                    </div>
                </div>
            </div>
            <div class="item col-sm-4">
                <div class="banner-boder-zoom2 banner-text">
                    <a href="#"><img src="catalog/view/theme/kute/images/data/option8/b3.jpg" alt="Banner"></a>
                    <div class="banner-content">
                        <h2 class="banner-title">FOR MEN</h2>
                        <div class="banner-desc">Deals Shop Always Open</div>
                        <a href="#" class="banner-button">Shop now</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- ./ top banner -->
<!-- tab product -->
<div class="block-tab-products">
    <div class="container">
        <ul class="nav-tab">
            <li class="active"><a data-toggle="tab" href="#tab1">FEATURED</a></li>
            <li><a data-toggle="tab" href="#tab2">BEST SELLERS </a></li>
            <li><a data-toggle="tab" href="#tab3">New Arrivals</a></li>
        </ul>
        <div class="tab-container">
            <div id="tab1" class="tab-panel active">
                <ul class="products-style8 row">
                    <li class="product col-sm-6 col-md-3">
                        <div class="product-container">
                            <div class="product-thumb">
                                <a href="#">
                                    <img class="primary_image" src="catalog/view/theme/kute/images/data/option8/p1.jpg" alt="Product">
                                    <img class="secondary_image" src="catalog/view/theme/kute/images/data/option8/p1-1.jpg" alt="Product">
                                </a>
                                <a title="Quick view" class="quick-view" href="#">Quick view</a>
                            </div>
                            <div class="product-info">
                                <div class="product-name">
                                    <a href="#">SEXY SUMMER DRESS</a>
                                </div>
                                <div class="box-price">
                                    <span class="price">$250</span>
                                    <span class="old-price">$350</span>
                                </div>
                                <div class="button-control">
                                    <a data-toggle="tooltip" data-placement="top" title="Add to Compare" class="compare" href="#">Compare</a>
                                    <a title="Add to cart" class="add-to-cart" href="#">Add to cart</a>
                                    <a data-toggle="tooltip" data-placement="top" title="Add to My Wishlist" class="wishlist" href="#">wishlist</a>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="product col-sm-6 col-md-3">
                        <div class="product-container">
                            <div class="product-thumb">
                                <a href="#">
                                    <img class="primary_image" src="catalog/view/theme/kute/images/data/option8/p2.jpg" alt="Product">
                                    <img class="secondary_image" src="catalog/view/theme/kute/images/data/option8/p2-1.jpg" alt="Product">
                                </a>
                                <a title="Quick view" class="quick-view" href="#">Quick view</a>
                            </div>
                            <div class="product-info">
                                <div class="product-name">
                                    <a href="#">SEXY SUMMER DRESS</a>
                                </div>
                                <div class="box-price">
                                    <span class="price">$250</span>
                                    <span class="old-price">$350</span>
                                </div>
                                <div class="button-control">
                                    <a data-toggle="tooltip" data-placement="top" title="Add to Compare" class="compare" href="#">Compare</a>
                                    <a title="Add to cart" class="add-to-cart" href="#">Add to cart</a>
                                    <a data-toggle="tooltip" data-placement="top" title="Add to My Wishlist" class="wishlist" href="#">wishlist</a>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="product col-sm-6 col-md-3">
                        <div class="product-container">
                            <div class="product-thumb">
                                <a href="#">
                                    <img class="primary_image" src="catalog/view/theme/kute/images/data/option8/p3.jpg" alt="Product">
                                    <img class="secondary_image" src="catalog/view/theme/kute/images/data/option8/p3-1.jpg" alt="Product">
                                </a>
                                <a title="Quick view" class="quick-view" href="#">Quick view</a>
                            </div>
                            <div class="product-info">
                                <div class="product-name">
                                    <a href="#">SEXY SUMMER DRESS</a>
                                </div>
                                <div class="box-price">
                                    <span class="price">$250</span>
                                    <span class="old-price">$350</span>
                                </div>
                                <div class="button-control">
                                    <a data-toggle="tooltip" data-placement="top" title="Add to Compare" class="compare" href="#">Compare</a>
                                    <a title="Add to cart" class="add-to-cart" href="#">Add to cart</a>
                                    <a data-toggle="tooltip" data-placement="top" title="Add to My Wishlist" class="wishlist" href="#">wishlist</a>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="product col-sm-6 col-md-3">
                        <div class="product-container">
                            <div class="product-thumb">
                                <a href="#">
                                    <img class="primary_image" src="catalog/view/theme/kute/images/data/option8/p4.jpg" alt="Product">
                                    <img class="secondary_image" src="catalog/view/theme/kute/images/data/option8/p4-1.jpg" alt="Product">
                                </a>
                                <a title="Quick view" class="quick-view" href="#">Quick view</a>
                            </div>
                            <div class="product-info">
                                <div class="product-name">
                                    <a href="#">SEXY SUMMER DRESS</a>
                                </div>
                                <div class="box-price">
                                    <span class="price">$250</span>
                                    <span class="old-price">$350</span>
                                </div>
                                <div class="button-control">
                                    <a data-toggle="tooltip" data-placement="top" title="Add to Compare" class="compare" href="#">Compare</a>
                                    <a title="Add to cart" class="add-to-cart" href="#">Add to cart</a>
                                    <a data-toggle="tooltip" data-placement="top" title="Add to My Wishlist" class="wishlist" href="#">wishlist</a>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="product col-sm-6 col-md-3">
                        <div class="product-container">
                            <div class="product-thumb">
                                <a href="#">
                                    <img class="primary_image" src="catalog/view/theme/kute/images/data/option8/p5.jpg" alt="Product">
                                    <img class="secondary_image" src="catalog/view/theme/kute/images/data/option8/p5-1.jpg" alt="Product">
                                </a>
                                <a title="Quick view" class="quick-view" href="#">Quick view</a>
                            </div>
                            <div class="product-info">
                                <div class="product-name">
                                    <a href="#">SEXY SUMMER DRESS</a>
                                </div>
                                <div class="box-price">
                                    <span class="price">$250</span>
                                    <span class="old-price">$350</span>
                                </div>
                                <div class="button-control">
                                    <a data-toggle="tooltip" data-placement="top" title="Add to Compare" class="compare" href="#">Compare</a>
                                    <a title="Add to cart" class="add-to-cart" href="#">Add to cart</a>
                                    <a data-toggle="tooltip" data-placement="top" title="Add to My Wishlist" class="wishlist" href="#">wishlist</a>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="product col-sm-6 col-md-3">
                        <div class="product-container">
                            <div class="product-thumb">
                                <a href="#">
                                    <img class="primary_image" src="catalog/view/theme/kute/images/data/option8/p6.jpg" alt="Product">
                                    <img class="secondary_image" src="catalog/view/theme/kute/images/data/option8/p6-1.jpg" alt="Product">
                                </a>
                                <a title="Quick view" class="quick-view" href="#">Quick view</a>
                            </div>
                            <div class="product-info">
                                <div class="product-name">
                                    <a href="#">SEXY SUMMER DRESS</a>
                                </div>
                                <div class="box-price">
                                    <span class="price">$250</span>
                                    <span class="old-price">$350</span>
                                </div>
                                <div class="button-control">
                                    <a data-toggle="tooltip" data-placement="top" title="Add to Compare" class="compare" href="#">Compare</a>
                                    <a title="Add to cart" class="add-to-cart" href="#">Add to cart</a>
                                    <a data-toggle="tooltip" data-placement="top" title="Add to My Wishlist" class="wishlist" href="#">wishlist</a>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="product col-sm-6 col-md-3">
                        <div class="product-container">
                            <div class="product-thumb">
                                <a href="#">
                                    <img class="primary_image" src="catalog/view/theme/kute/images/data/option8/p7.jpg" alt="Product">
                                    <img class="secondary_image" src="catalog/view/theme/kute/images/data/option8/p7-1.jpg" alt="Product">
                                </a>
                                <a title="Quick view" class="quick-view" href="#">Quick view</a>
                            </div>
                            <div class="product-info">
                                <div class="product-name">
                                    <a href="#">SEXY SUMMER DRESS</a>
                                </div>
                                <div class="box-price">
                                    <span class="price">$250</span>
                                    <span class="old-price">$350</span>
                                </div>
                                <div class="button-control">
                                    <a data-toggle="tooltip" data-placement="top" title="Add to Compare" class="compare" href="#">Compare</a>
                                    <a title="Add to cart" class="add-to-cart" href="#">Add to cart</a>
                                    <a data-toggle="tooltip" data-placement="top" title="Add to My Wishlist" class="wishlist" href="#">wishlist</a>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="product col-sm-6 col-md-3">
                        <div class="product-container">
                            <div class="product-thumb">
                                <a href="#">
                                    <img class="primary_image" src="catalog/view/theme/kute/images/data/option8/p8.jpg" alt="Product">
                                    <img class="secondary_image" src="catalog/view/theme/kute/images/data/option8/p8-1.jpg" alt="Product">
                                </a>
                                <a title="Quick view" class="quick-view" href="#">Quick view</a>
                            </div>
                            <div class="product-info">
                                <div class="product-name">
                                    <a href="#">SEXY SUMMER DRESS</a>
                                </div>
                                <div class="box-price">
                                    <span class="price">$250</span>
                                    <span class="old-price">$350</span>
                                </div>
                                <div class="button-control">
                                    <a data-toggle="tooltip" data-placement="top" title="Add to Compare" class="compare" href="#">Compare</a>
                                    <a title="Add to cart" class="add-to-cart" href="#">Add to cart</a>
                                    <a data-toggle="tooltip" data-placement="top" title="Add to My Wishlist" class="wishlist" href="#">wishlist</a>
                                </div>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
            <div id="tab2" class="tab-panel">
                <ul class="products-style8 row">
                    <li class="product col-sm-6 col-md-3">
                        <div class="product-container">
                            <div class="product-thumb">
                                <a href="#">
                                    <img class="primary_image" src="catalog/view/theme/kute/images/data/option8/p1.jpg" alt="Product">
                                    <img class="secondary_image" src="catalog/view/theme/kute/images/data/option8/p1-1.jpg" alt="Product">
                                </a>
                                <a title="Quick view" class="quick-view" href="#">Quick view</a>
                            </div>
                            <div class="product-info">
                                <div class="product-name">
                                    <a href="#">SEXY SUMMER DRESS</a>
                                </div>
                                <div class="box-price">
                                    <span class="price">$250</span>
                                    <span class="old-price">$350</span>
                                </div>
                                <div class="button-control">
                                    <a data-toggle="tooltip" data-placement="top" title="Add to Compare" class="compare" href="#">Compare</a>
                                    <a title="Add to cart" class="add-to-cart" href="#">Add to cart</a>
                                    <a data-toggle="tooltip" data-placement="top" title="Add to My Wishlist" class="wishlist" href="#">wishlist</a>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="product col-sm-6 col-md-3">
                        <div class="product-container">
                            <div class="product-thumb">
                                <a href="#">
                                    <img class="primary_image" src="catalog/view/theme/kute/images/data/option8/p2.jpg" alt="Product">
                                    <img class="secondary_image" src="catalog/view/theme/kute/images/data/option8/p2-1.jpg" alt="Product">
                                </a>
                                <a title="Quick view" class="quick-view" href="#">Quick view</a>
                            </div>
                            <div class="product-info">
                                <div class="product-name">
                                    <a href="#">SEXY SUMMER DRESS</a>
                                </div>
                                <div class="box-price">
                                    <span class="price">$250</span>
                                    <span class="old-price">$350</span>
                                </div>
                                <div class="button-control">
                                    <a data-toggle="tooltip" data-placement="top" title="Add to Compare" class="compare" href="#">Compare</a>
                                    <a title="Add to cart" class="add-to-cart" href="#">Add to cart</a>
                                    <a data-toggle="tooltip" data-placement="top" title="Add to My Wishlist" class="wishlist" href="#">wishlist</a>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="product col-sm-6 col-md-3">
                        <div class="product-container">
                            <div class="product-thumb">
                                <a href="#">
                                    <img class="primary_image" src="catalog/view/theme/kute/images/data/option8/p3.jpg" alt="Product">
                                    <img class="secondary_image" src="catalog/view/theme/kute/images/data/option8/p3-1.jpg" alt="Product">
                                </a>
                                <a title="Quick view" class="quick-view" href="#">Quick view</a>
                            </div>
                            <div class="product-info">
                                <div class="product-name">
                                    <a href="#">SEXY SUMMER DRESS</a>
                                </div>
                                <div class="box-price">
                                    <span class="price">$250</span>
                                    <span class="old-price">$350</span>
                                </div>
                                <div class="button-control">
                                    <a data-toggle="tooltip" data-placement="top" title="Add to Compare" class="compare" href="#">Compare</a>
                                    <a title="Add to cart" class="add-to-cart" href="#">Add to cart</a>
                                    <a data-toggle="tooltip" data-placement="top" title="Add to My Wishlist" class="wishlist" href="#">wishlist</a>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="product col-sm-6 col-md-3">
                        <div class="product-container">
                            <div class="product-thumb">
                                <a href="#">
                                    <img class="primary_image" src="catalog/view/theme/kute/images/data/option8/p4.jpg" alt="Product">
                                    <img class="secondary_image" src="catalog/view/theme/kute/images/data/option8/p4-1.jpg" alt="Product">
                                </a>
                                <a title="Quick view" class="quick-view" href="#">Quick view</a>
                            </div>
                            <div class="product-info">
                                <div class="product-name">
                                    <a href="#">SEXY SUMMER DRESS</a>
                                </div>
                                <div class="box-price">
                                    <span class="price">$250</span>
                                    <span class="old-price">$350</span>
                                </div>
                                <div class="button-control">
                                    <a data-toggle="tooltip" data-placement="top" title="Add to Compare" class="compare" href="#">Compare</a>
                                    <a title="Add to cart" class="add-to-cart" href="#">Add to cart</a>
                                    <a data-toggle="tooltip" data-placement="top" title="Add to My Wishlist" class="wishlist" href="#">wishlist</a>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="product col-sm-6 col-md-3">
                        <div class="product-container">
                            <div class="product-thumb">
                                <a href="#">
                                    <img class="primary_image" src="catalog/view/theme/kute/images/data/option8/p5.jpg" alt="Product">
                                    <img class="secondary_image" src="catalog/view/theme/kute/images/data/option8/p5-1.jpg" alt="Product">
                                </a>
                                <a title="Quick view" class="quick-view" href="#">Quick view</a>
                            </div>
                            <div class="product-info">
                                <div class="product-name">
                                    <a href="#">SEXY SUMMER DRESS</a>
                                </div>
                                <div class="box-price">
                                    <span class="price">$250</span>
                                    <span class="old-price">$350</span>
                                </div>
                                <div class="button-control">
                                    <a data-toggle="tooltip" data-placement="top" title="Add to Compare" class="compare" href="#">Compare</a>
                                    <a title="Add to cart" class="add-to-cart" href="#">Add to cart</a>
                                    <a data-toggle="tooltip" data-placement="top" title="Add to My Wishlist" class="wishlist" href="#">wishlist</a>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="product col-sm-6 col-md-3">
                        <div class="product-container">
                            <div class="product-thumb">
                                <a href="#">
                                    <img class="primary_image" src="catalog/view/theme/kute/images/data/option8/p6.jpg" alt="Product">
                                    <img class="secondary_image" src="catalog/view/theme/kute/images/data/option8/p6-1.jpg" alt="Product">
                                </a>
                                <a title="Quick view" class="quick-view" href="#">Quick view</a>
                            </div>
                            <div class="product-info">
                                <div class="product-name">
                                    <a href="#">SEXY SUMMER DRESS</a>
                                </div>
                                <div class="box-price">
                                    <span class="price">$250</span>
                                    <span class="old-price">$350</span>
                                </div>
                                <div class="button-control">
                                    <a data-toggle="tooltip" data-placement="top" title="Add to Compare" class="compare" href="#">Compare</a>
                                    <a title="Add to cart" class="add-to-cart" href="#">Add to cart</a>
                                    <a data-toggle="tooltip" data-placement="top" title="Add to My Wishlist" class="wishlist" href="#">wishlist</a>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="product col-sm-6 col-md-3">
                        <div class="product-container">
                            <div class="product-thumb">
                                <a href="#">
                                    <img class="primary_image" src="catalog/view/theme/kute/images/data/option8/p7.jpg" alt="Product">
                                    <img class="secondary_image" src="catalog/view/theme/kute/images/data/option8/p7-1.jpg" alt="Product">
                                </a>
                                <a title="Quick view" class="quick-view" href="#">Quick view</a>
                            </div>
                            <div class="product-info">
                                <div class="product-name">
                                    <a href="#">SEXY SUMMER DRESS</a>
                                </div>
                                <div class="box-price">
                                    <span class="price">$250</span>
                                    <span class="old-price">$350</span>
                                </div>
                                <div class="button-control">
                                    <a data-toggle="tooltip" data-placement="top" title="Add to Compare" class="compare" href="#">Compare</a>
                                    <a title="Add to cart" class="add-to-cart" href="#">Add to cart</a>
                                    <a data-toggle="tooltip" data-placement="top" title="Add to My Wishlist" class="wishlist" href="#">wishlist</a>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="product col-sm-6 col-md-3">
                        <div class="product-container">
                            <div class="product-thumb">
                                <a href="#">
                                    <img class="primary_image" src="catalog/view/theme/kute/images/data/option8/p8.jpg" alt="Product">
                                    <img class="secondary_image" src="catalog/view/theme/kute/images/data/option8/p8-1.jpg" alt="Product">
                                </a>
                                <a title="Quick view" class="quick-view" href="#">Quick view</a>
                            </div>
                            <div class="product-info">
                                <div class="product-name">
                                    <a href="#">SEXY SUMMER DRESS</a>
                                </div>
                                <div class="box-price">
                                    <span class="price">$250</span>
                                    <span class="old-price">$350</span>
                                </div>
                                <div class="button-control">
                                    <a data-toggle="tooltip" data-placement="top" title="Add to Compare" class="compare" href="#">Compare</a>
                                    <a title="Add to cart" class="add-to-cart" href="#">Add to cart</a>
                                    <a data-toggle="tooltip" data-placement="top" title="Add to My Wishlist" class="wishlist" href="#">wishlist</a>
                                </div>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
            <div id="tab3" class="tab-panel">
                <ul class="products-style8 row">
                    <li class="product col-sm-6 col-md-3">
                        <div class="product-container">
                            <div class="product-thumb">
                                <a href="#">
                                    <img class="primary_image" src="catalog/view/theme/kute/images/data/option8/p1.jpg" alt="Product">
                                    <img class="secondary_image" src="catalog/view/theme/kute/images/data/option8/p1-1.jpg" alt="Product">
                                </a>
                                <a title="Quick view" class="quick-view" href="#">Quick view</a>
                            </div>
                            <div class="product-info">
                                <div class="product-name">
                                    <a href="#">SEXY SUMMER DRESS</a>
                                </div>
                                <div class="box-price">
                                    <span class="price">$250</span>
                                    <span class="old-price">$350</span>
                                </div>
                                <div class="button-control">
                                    <a data-toggle="tooltip" data-placement="top" title="Add to Compare" class="compare" href="#">Compare</a>
                                    <a title="Add to cart" class="add-to-cart" href="#">Add to cart</a>
                                    <a data-toggle="tooltip" data-placement="top" title="Add to My Wishlist" class="wishlist" href="#">wishlist</a>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="product col-sm-6 col-md-3">
                        <div class="product-container">
                            <div class="product-thumb">
                                <a href="#">
                                    <img class="primary_image" src="catalog/view/theme/kute/images/data/option8/p2.jpg" alt="Product">
                                    <img class="secondary_image" src="catalog/view/theme/kute/images/data/option8/p2-1.jpg" alt="Product">
                                </a>
                                <a title="Quick view" class="quick-view" href="#">Quick view</a>
                            </div>
                            <div class="product-info">
                                <div class="product-name">
                                    <a href="#">SEXY SUMMER DRESS</a>
                                </div>
                                <div class="box-price">
                                    <span class="price">$250</span>
                                    <span class="old-price">$350</span>
                                </div>
                                <div class="button-control">
                                    <a data-toggle="tooltip" data-placement="top" title="Add to Compare" class="compare" href="#">Compare</a>
                                    <a title="Add to cart" class="add-to-cart" href="#">Add to cart</a>
                                    <a data-toggle="tooltip" data-placement="top" title="Add to My Wishlist" class="wishlist" href="#">wishlist</a>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="product col-sm-6 col-md-3">
                        <div class="product-container">
                            <div class="product-thumb">
                                <a href="#">
                                    <img class="primary_image" src="catalog/view/theme/kute/images/data/option8/p3.jpg" alt="Product">
                                    <img class="secondary_image" src="catalog/view/theme/kute/images/data/option8/p3-1.jpg" alt="Product">
                                </a>
                                <a title="Quick view" class="quick-view" href="#">Quick view</a>
                            </div>
                            <div class="product-info">
                                <div class="product-name">
                                    <a href="#">SEXY SUMMER DRESS</a>
                                </div>
                                <div class="box-price">
                                    <span class="price">$250</span>
                                    <span class="old-price">$350</span>
                                </div>
                                <div class="button-control">
                                    <a data-toggle="tooltip" data-placement="top" title="Add to Compare" class="compare" href="#">Compare</a>
                                    <a title="Add to cart" class="add-to-cart" href="#">Add to cart</a>
                                    <a data-toggle="tooltip" data-placement="top" title="Add to My Wishlist" class="wishlist" href="#">wishlist</a>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="product col-sm-6 col-md-3">
                        <div class="product-container">
                            <div class="product-thumb">
                                <a href="#">
                                    <img class="primary_image" src="catalog/view/theme/kute/images/data/option8/p4.jpg" alt="Product">
                                    <img class="secondary_image" src="catalog/view/theme/kute/images/data/option8/p4-1.jpg" alt="Product">
                                </a>
                                <a title="Quick view" class="quick-view" href="#">Quick view</a>
                            </div>
                            <div class="product-info">
                                <div class="product-name">
                                    <a href="#">SEXY SUMMER DRESS</a>
                                </div>
                                <div class="box-price">
                                    <span class="price">$250</span>
                                    <span class="old-price">$350</span>
                                </div>
                                <div class="button-control">
                                    <a data-toggle="tooltip" data-placement="top" title="Add to Compare" class="compare" href="#">Compare</a>
                                    <a title="Add to cart" class="add-to-cart" href="#">Add to cart</a>
                                    <a data-toggle="tooltip" data-placement="top" title="Add to My Wishlist" class="wishlist" href="#">wishlist</a>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="product col-sm-6 col-md-3">
                        <div class="product-container">
                            <div class="product-thumb">
                                <a href="#">
                                    <img class="primary_image" src="catalog/view/theme/kute/images/data/option8/p5.jpg" alt="Product">
                                    <img class="secondary_image" src="catalog/view/theme/kute/images/data/option8/p5-1.jpg" alt="Product">
                                </a>
                                <a title="Quick view" class="quick-view" href="#">Quick view</a>
                            </div>
                            <div class="product-info">
                                <div class="product-name">
                                    <a href="#">SEXY SUMMER DRESS</a>
                                </div>
                                <div class="box-price">
                                    <span class="price">$250</span>
                                    <span class="old-price">$350</span>
                                </div>
                                <div class="button-control">
                                    <a data-toggle="tooltip" data-placement="top" title="Add to Compare" class="compare" href="#">Compare</a>
                                    <a title="Add to cart" class="add-to-cart" href="#">Add to cart</a>
                                    <a data-toggle="tooltip" data-placement="top" title="Add to My Wishlist" class="wishlist" href="#">wishlist</a>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="product col-sm-6 col-md-3">
                        <div class="product-container">
                            <div class="product-thumb">
                                <a href="#">
                                    <img class="primary_image" src="catalog/view/theme/kute/images/data/option8/p6.jpg" alt="Product">
                                    <img class="secondary_image" src="catalog/view/theme/kute/images/data/option8/p6-1.jpg" alt="Product">
                                </a>
                                <a title="Quick view" class="quick-view" href="#">Quick view</a>
                            </div>
                            <div class="product-info">
                                <div class="product-name">
                                    <a href="#">SEXY SUMMER DRESS</a>
                                </div>
                                <div class="box-price">
                                    <span class="price">$250</span>
                                    <span class="old-price">$350</span>
                                </div>
                                <div class="button-control">
                                    <a data-toggle="tooltip" data-placement="top" title="Add to Compare" class="compare" href="#">Compare</a>
                                    <a title="Add to cart" class="add-to-cart" href="#">Add to cart</a>
                                    <a data-toggle="tooltip" data-placement="top" title="Add to My Wishlist" class="wishlist" href="#">wishlist</a>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="product col-sm-6 col-md-3">
                        <div class="product-container">
                            <div class="product-thumb">
                                <a href="#">
                                    <img class="primary_image" src="catalog/view/theme/kute/images/data/option8/p7.jpg" alt="Product">
                                    <img class="secondary_image" src="catalog/view/theme/kute/images/data/option8/p7-1.jpg" alt="Product">
                                </a>
                                <a title="Quick view" class="quick-view" href="#">Quick view</a>
                            </div>
                            <div class="product-info">
                                <div class="product-name">
                                    <a href="#">SEXY SUMMER DRESS</a>
                                </div>
                                <div class="box-price">
                                    <span class="price">$250</span>
                                    <span class="old-price">$350</span>
                                </div>
                                <div class="button-control">
                                    <a data-toggle="tooltip" data-placement="top" title="Add to Compare" class="compare" href="#">Compare</a>
                                    <a title="Add to cart" class="add-to-cart" href="#">Add to cart</a>
                                    <a data-toggle="tooltip" data-placement="top" title="Add to My Wishlist" class="wishlist" href="#">wishlist</a>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="product col-sm-6 col-md-3">
                        <div class="product-container">
                            <div class="product-thumb">
                                <a href="#">
                                    <img class="primary_image" src="catalog/view/theme/kute/images/data/option8/p8.jpg" alt="Product">
                                    <img class="secondary_image" src="catalog/view/theme/kute/images/data/option8/p8-1.jpg" alt="Product">
                                </a>
                                <a title="Quick view" class="quick-view" href="#">Quick view</a>
                            </div>
                            <div class="product-info">
                                <div class="product-name">
                                    <a href="#">SEXY SUMMER DRESS</a>
                                </div>
                                <div class="box-price">
                                    <span class="price">$250</span>
                                    <span class="old-price">$350</span>
                                </div>
                                <div class="button-control">
                                    <a data-toggle="tooltip" data-placement="top" title="Add to Compare" class="compare" href="#">Compare</a>
                                    <a title="Add to cart" class="add-to-cart" href="#">Add to cart</a>
                                    <a data-toggle="tooltip" data-placement="top" title="Add to My Wishlist" class="wishlist" href="#">wishlist</a>
                                </div>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- ./tab product -->
<!-- loock boocks -->
<section class="section8 block-loock-bocks parallax">
    <div class="section-container">
        <h3 class="section-title">LOOK BOOKS</h3>
        <div class="section-content">
            <div class="container">
                <ul class="loock-boock-list row">
                    <li class="col-sm-3">
                        <div class="image">
                            <a href="#"><img src="catalog/view/theme/kute/images/data/option8/loock-boock1.jpg" alt="Loock boocks"></a>
                        </div>
                        <div class="info">
                            <p class="name">Paulette</p>
                            <p class="location">Australia</p>

                        </div>
                    </li>
                    <li class="col-sm-3">
                        <div class="image">
                            <a href="#"><img src="catalog/view/theme/kute/images/data/option8/loock-boock2.jpg" alt="Loock boocks"></a>
                        </div>
                        <div class="info">
                            <p class="name">Paulette</p>
                            <p class="location">Australia</p>
                            
                        </div>
                    </li>
                    <li class="col-sm-3">
                        <div class="image">
                            <a href="#"><img src="catalog/view/theme/kute/images/data/option8/loock-boock3.jpg" alt="Loock boocks"></a>
                        </div>
                        <div class="info">
                            <p class="name">Paulette</p>
                            <p class="location">Australia</p>
                            
                        </div>
                    </li>
                    <li class="col-sm-3">
                        <div class="image">
                            <a href="#"><img src="catalog/view/theme/kute/images/data/option8/loock-boock4.jpg" alt="Loock boocks"></a>
                        </div>
                        <div class="info">
                            <p class="name">Paulette</p>
                            <p class="location">Australia</p>
                            
                        </div>
                    </li>
                </ul>
                <div class="lock-boock-button">
                    <a href="#">Submit Your Photos</a>
                    <a href="#">View All</a>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- ./loock boocks -->
<!-- Block trending -->
<section class="section8 block-trending">
    <div class="section-container">
        <h3 class="section-title">trending now</h3>
        <div class="section-content">
            <div class="container">
                <ul class="products-style8 owl-carousel"  data-dots="false" data-loop="true" data-nav = "true" data-margin = "29" data-autoplayTimeout="1000" data-autoplayHoverPause = "true" data-responsive='{"0":{"items":1},"600":{"items":2},"1000":{"items":4}}'>
                    <li class="product">
                        <div class="product-container">
                            <div class="product-thumb">
                                <a href="#">
                                    <img class="primary_image" src="catalog/view/theme/kute/images/data/option8/p9.jpg" alt="Product">
                                    <img class="secondary_image" src="catalog/view/theme/kute/images/data/option8/p9-1.jpg" alt="Product">
                                </a>
                                <a title="Quick view" class="quick-view" href="#">Quick view</a>
                            </div>
                            <div class="product-info">
                                <div class="product-name">
                                    <a href="#">SEXY SUMMER DRESS</a>
                                </div>
                                <div class="box-price">
                                    <span class="price">$250</span>
                                    <span class="old-price">$350</span>
                                </div>
                                <div class="button-control">
                                    <a data-toggle="tooltip" data-placement="top" title="Add to Compare" class="compare" href="#">Compare</a>
                                    <a title="Add to cart" class="add-to-cart" href="#">Add to cart</a>
                                    <a data-toggle="tooltip" data-placement="top" title="Add to My Wishlist" class="wishlist" href="#">wishlist</a>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="product">
                        <div class="product-container">
                            <div class="product-thumb">
                                <a href="#">
                                    <img class="primary_image" src="catalog/view/theme/kute/images/data/option8/p10.jpg" alt="Product">
                                    <img class="secondary_image" src="catalog/view/theme/kute/images/data/option8/p10-1.jpg" alt="Product">
                                </a>
                                <a title="Quick view" class="quick-view" href="#">Quick view</a>
                            </div>
                            <div class="product-info">
                                <div class="product-name">
                                    <a href="#">SEXY SUMMER DRESS</a>
                                </div>
                                <div class="box-price">
                                    <span class="price">$250</span>
                                    <span class="old-price">$350</span>
                                </div>
                                <div class="button-control">
                                    <a data-toggle="tooltip" data-placement="top" title="Add to Compare" class="compare" href="#">Compare</a>
                                    <a title="Add to cart" class="add-to-cart" href="#">Add to cart</a>
                                    <a data-toggle="tooltip" data-placement="top" title="Add to My Wishlist" class="wishlist" href="#">wishlist</a>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="product">
                        <div class="product-container">
                            <div class="product-thumb">
                                <a href="#">
                                    <img class="primary_image" src="catalog/view/theme/kute/images/data/option8/p11.jpg" alt="Product">
                                    <img class="secondary_image" src="catalog/view/theme/kute/images/data/option8/p11-1.jpg" alt="Product">
                                </a>
                                <a title="Quick view" class="quick-view" href="#">Quick view</a>
                            </div>
                            <div class="product-info">
                                <div class="product-name">
                                    <a href="#">SEXY SUMMER DRESS</a>
                                </div>
                                <div class="box-price">
                                    <span class="price">$250</span>
                                    <span class="old-price">$350</span>
                                </div>
                                <div class="button-control">
                                    <a data-toggle="tooltip" data-placement="top" title="Add to Compare" class="compare" href="#">Compare</a>
                                    <a title="Add to cart" class="add-to-cart" href="#">Add to cart</a>
                                    <a data-toggle="tooltip" data-placement="top" title="Add to My Wishlist" class="wishlist" href="#">wishlist</a>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li class="product">
                        <div class="product-container">
                            <div class="product-thumb">
                                <a href="#">
                                    <img class="primary_image" src="catalog/view/theme/kute/images/data/option8/p12.jpg" alt="Product">
                                    <img class="secondary_image" src="catalog/view/theme/kute/images/data/option8/p12-1.jpg" alt="Product">
                                </a>
                                <a title="Quick view" class="quick-view" href="#">Quick view</a>
                            </div>
                            <div class="product-info">
                                <div class="product-name">
                                    <a href="#">SEXY SUMMER DRESS</a>
                                </div>
                                <div class="box-price">
                                    <span class="price">$250</span>
                                    <span class="old-price">$350</span>
                                </div>
                                <div class="button-control">
                                    <a data-toggle="tooltip" data-placement="top" title="Add to Compare" class="compare" href="#">Compare</a>
                                    <a title="Add to cart" class="add-to-cart" href="#">Add to cart</a>
                                    <a data-toggle="tooltip" data-placement="top" title="Add to My Wishlist" class="wishlist" href="#">wishlist</a>
                                </div>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</section>
<!-- ./Block trending -->
<!-- Block trending -->
<section class="section8 block-collections">
    <div class="section-container">
        <h3 class="section-title">Collections</h3>
        <div class="section-content">
            <div class="container">
                <ul class="nav-tab">
                    <li class="active"><a data-toggle="tab" href="#collection1">FOR WOMEN</a></li>
                    <li><a data-toggle="tab" href="#collection2">FOR MEN</a></li>
                </ul>
                <div class="tab-container">
                    <div id="collection1" class="tab-panel active">
                        <ul class="collection-list owl-carousel" data-dots="false" data-loop="true" data-nav = "true" data-margin = "14" data-autoplayTimeout="1000" data-autoplayHoverPause = "true" data-responsive='{"0":{"items":1},"600":{"items":2},"1000":{"items":3}}'>
                            <li class="item">
                                <div class="image banner-boder-zoom2">
                                    <a href="#"><img src="catalog/view/theme/kute/images/data/option8/collection1.jpg" alt="collection1"></a>
                                </div>
                                <div class="info">
                                    <h3 class="title"><a href="#">Evening sexy dress</a></h3>
                                    <div class="desc">
                                        It looks great, feel comfortable and best of all, fit any occasion. 100% Cotton and Made in France
                                    </div>
                                    <div class="author">Designed by: James Watt</div>
                                    <div class="collection-button">
                                        <a href="#">View Collection</a>
                                    </div>
                                </div>
                            </li>
                            <li class="item top">
                                <div class="info">
                                    <h3 class="title"><a href="#">Evening sexy dress</a></h3>
                                    <div class="desc">
                                        It looks great, feel comfortable and best of all, fit any occasion. 100% Cotton and Made in France
                                    </div>
                                    <div class="author">Designed by: James Watt</div>
                                    <div class="collection-button">
                                        <a href="#">View Collection</a>
                                    </div>
                                </div>
                                <div class="image banner-boder-zoom2">
                                    <a href="#"><img src="catalog/view/theme/kute/images/data/option8/collection2.jpg" alt="collection1"></a>
                                </div>
                            </li>
                            <li class="item">
                                <div class="image banner-boder-zoom2">
                                    <a href="#"><img src="catalog/view/theme/kute/images/data/option8/collection3.jpg" alt="collection1"></a>
                                </div>
                                <div class="info">
                                    <h3 class="title"><a href="#">Evening sexy dress</a></h3>
                                    <div class="desc">
                                        It looks great, feel comfortable and best of all, fit any occasion. 100% Cotton and Made in France
                                    </div>
                                    <div class="author">Designed by: James Watt</div>
                                    <div class="collection-button">
                                        <a href="#">View Collection</a>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div id="collection2" class="tab-panel">
                        <ul class="collection-list owl-carousel" data-dots="false" data-loop="true" data-nav = "true" data-margin = "14" data-autoplayTimeout="1000" data-autoplayHoverPause = "true" data-responsive='{"0":{"items":1},"600":{"items":2},"1000":{"items":3}}'>
                            <li class="item">
                                <div class="image banner-boder-zoom2">
                                    <a href="#"><img src="catalog/view/theme/kute/images/data/option8/collection4.jpg" alt="collection1"></a>
                                </div>
                                <div class="info">
                                    <h3 class="title"><a href="#">Evening sexy dress</a></h3>
                                    <div class="desc">
                                        It looks great, feel comfortable and best of all, fit any occasion. 100% Cotton and Made in France
                                    </div>
                                    <div class="author">Designed by: James Watt</div>
                                    <div class="collection-button">
                                        <a href="#">View Collection</a>
                                    </div>
                                </div>
                            </li>
                            <li class="item top">
                                <div class="info">
                                    <h3 class="title"><a href="#">Evening sexy dress</a></h3>
                                    <div class="desc">
                                        It looks great, feel comfortable and best of all, fit any occasion. 100% Cotton and Made in France
                                    </div>
                                    <div class="author">Designed by: James Watt</div>
                                    <div class="collection-button">
                                        <a href="#">View Collection</a>
                                    </div>
                                </div>
                                <div class="image banner-boder-zoom2">
                                    <a href="#"><img src="catalog/view/theme/kute/images/data/option8/collection5.jpg" alt="collection1"></a>
                                </div>
                            </li>
                            <li class="item">
                                <div class="image banner-boder-zoom2">
                                    <a href="#"><img src="catalog/view/theme/kute/images/data/option8/collection6.jpg" alt="collection1"></a>
                                </div>
                                <div class="info">
                                    <h3 class="title"><a href="#">Evening sexy dress</a></h3>
                                    <div class="desc">
                                        It looks great, feel comfortable and best of all, fit any occasion. 100% Cotton and Made in France
                                    </div>
                                    <div class="author">Designed by: James Watt</div>
                                    <div class="collection-button">
                                        <a href="#">View Collection</a>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- ./Block trending -->
<!-- Block testimonials -->
<section class="section8 block-testimonials parallax">
    <div class="section-container">
        <h3 class="section-title">Testimonials</h3>
        <div class="section-content">
            <div class="container">
                <div class="testimonial-wapper">
                    <div class="testimonials">
                        <ul class="effect-myZoomIn testimonial testimonial-carousel">
                            <li>
                                <div class="testimonial-image">
                                    <a href="#"><img src="catalog/view/theme/kute/images/data/option8/testimonials1.jpg" alt="testimonials"></a>
                                </div>
                                <div class="info">
                                    <p>We combine industry expertise with innovative technology to deliver critical information to leading decision makers , We combine industry expertise with innovative technology to deliver critical information to leading decision makers. Thank you very much for youe services!</p>
                                    <p class="testimonial-nane">Karla Anderson - Happy Customer</p>
                                </div>
                            </li>
                            <li>
                                <div class="testimonial-image">
                                    <a href="#"><img src="catalog/view/theme/kute/images/data/option8/testimonials2.jpg" alt="testimonials"></a>
                                </div>
                                <div class="info">
                                    <p>Curabitur non nulla sit amet nisl tempus convallis quis ac lectus. Nulla porttitor accumsan tincidunt. Pellentesque in ipsum id orci porta dapibus. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
                                    <p class="testimonial-nane">Karla Anderson - Happy Customer</p>
                                </div>
                            </li>
                            <li>
                                <div class="testimonial-image">
                                    <a href="#"><img src="catalog/view/theme/kute/images/data/option8/testimonials3.jpg" alt="testimonials"></a>
                                </div>
                                <div class="info">
                                    <p>Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Ut a nisl id ante tempus hendrerit. Vivamus aliquet elit ac nisl. Duis arcu tortor, suscipit eget, imperdiet nec, imperdiet iaculis, ipsum. Maecenas malesuada.</p>
                                    <p class="testimonial-nane">Karla Anderson - Happy Customer</p>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="testimonial-caption"></div>
            </div>
        </div>
    </div>
</section>
<!-- ./Block testimonials -->

<!-- Block blog -->
<section class="section8 block-blogs">
    <div class="section-container">
        <h3 class="section-title">Lastest Posts</h3>
        <div class="section-content">
            <div class="container blog-list">
                <div class="blog-list-wapper">
                    <ul class="owl-carousel" data-dots="false" data-loop="true" data-nav = "true" data-margin = "30" data-autoplayTimeout="1000" data-autoplayHoverPause = "true" data-responsive='{"0":{"items":1},"600":{"items":3},"1000":{"items":4}}'>
                        <li>
                            <div class="post-thumb image-hover2">
                                <a href="#"><img src="catalog/view/theme/kute/images/data/option8/blog1.jpg" alt="Blog"></a>
                            </div>
                            <div class="post-desc">
                                <h5 class="post-title">
                                    <a href="#">Share the love with KuteShop</a>
                                </h5>
                                <div class="post-meta">
                                    <span class="date">February 27, 2015</span>
                                    <span class="comment">27 comment</span>
                                </div>
                                <div class="readmore">
                                    <a href="#">Readmore</a>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="post-thumb image-hover2">
                                <a href="#"><img src="catalog/view/theme/kute/images/data/option8/blog2.jpg" alt="Blog"></a>
                            </div>
                            <div class="post-desc">
                                <h5 class="post-title">
                                    <a href="#">Share the love with KuteShop</a>
                                </h5>
                                <div class="post-meta">
                                    <span class="date">February 27, 2015</span>
                                    <span class="comment">27 comment</span>
                                </div>
                                <div class="readmore">
                                    <a href="#">Readmore</a>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="post-thumb image-hover2">
                                <a href="#"><img src="catalog/view/theme/kute/images/data/option8/blog3.jpg" alt="Blog"></a>
                            </div>
                            <div class="post-desc">
                                <h5 class="post-title">
                                    <a href="#">Big sales this summer</a>
                                </h5>
                                <div class="post-meta">
                                    <span class="date">February 27, 2015</span>
                                    <span class="comment">27 comment</span>
                                </div>
                                <div class="readmore">
                                    <a href="#">Readmore</a>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="post-thumb image-hover2">
                                <a href="#"><img src="catalog/view/theme/kute/images/data/option8/blog4.jpg" alt="Blog"></a>
                            </div>
                            <div class="post-desc">
                                <h5 class="post-title">
                                    <a href="#">How to shop with us</a>
                                </h5>
                                <div class="post-meta">
                                    <span class="date">February 27, 2015</span>
                                    <span class="comment">27 comment</span>
                                </div>
                                <div class="readmore">
                                    <a href="#">Readmore</a>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- ./Block blog -->
<div class="block-manufacturer-logo">
    <div class="container">
        <ul class="owl-carousel" data-dots="false" data-loop="true" data-nav = "true" data-margin = "30" data-autoplayTimeout="1000" data-autoplayHoverPause = "true" data-autoplay="true" data-responsive='{"0":{"items":1},"480":{"items":2},"600":{"items":4},"1000":{"items":6}}'>
            <li><a href="#"><img src="catalog/view/theme/kute/images/data/option8/l1.jpg" alt="Logo"></a></li>
            <li><a href="#"><img src="catalog/view/theme/kute/images/data/option8/l2.jpg" alt="Logo"></a></li>
            <li><a href="#"><img src="catalog/view/theme/kute/images/data/option8/l3.jpg" alt="Logo"></a></li>
            <li><a href="#"><img src="catalog/view/theme/kute/images/data/option8/l4.jpg" alt="Logo"></a></li>
            <li><a href="#"><img src="catalog/view/theme/kute/images/data/option8/l5.jpg" alt="Logo"></a></li>
            <li><a href="#"><img src="catalog/view/theme/kute/images/data/option8/l6.jpg" alt="Logo"></a></li>
        </ul>
    </div>
</div>