 <!-- #trademark-text-box -->
    <div id="trademark-text-box" class="row">
        <div class="col-sm-12">
            <ul id="trademark-search-list" class="trademark-list">
                <li class="trademark-text-tit">HOT SEARCHED KEYWORDS:</li>
                <li><a href="#" >Xiaomo Mi3</a></li>
                <li><a href="#" >Digifli Pro XT 712 Tablet</a></li>
                <li><a href="#" >Mi 3 Phones</a></li>
                <li><a href="#" >Iphoneo 6 Plus</a></li>
                <li><a href="#" >Women's Messenger Bags</a></li>
                <li><a href="#" >Wallets</a></li>
                <li><a href="#" >Women's Clutches</a></li>
                <li><a href="#" >Backpacks Totes</a></li>
            </ul>
        </div>
        <div class="col-sm-12">
            <ul id="trademark-tv-list" class="trademark-list">
                <li class="trademark-text-tit">TVS:</li>
                <li><a href="#" >Sonyo TV</a></li>
                <li><a href="#" >Samsing TV</a></li>
                <li><a href="#" >LGG TV</a></li>
                <li><a href="#" >Onidai TV</a></li>
                <li><a href="#" >Toshibao TV</a></li>
                <li><a href="#" >Philipsi TV</a></li>
                <li><a href="#" >Micromax TV</a></li>
                <li><a href="#" >LED TV</a></li>
                <li><a href="#" >LCD TV</a></li>
                <li><a href="#" >Plasma TV</a></li>
                <li><a href="#" >3D TV</a></li>
                <li><a href="#" >Smart TV</a></li>
            </ul>
        </div>
        <div class="col-sm-12">
            <ul id="trademark-mobile-list" class="trademark-list">
                <li class="trademark-text-tit">MOBILES:</li>  
                <li><a href="#" >Moto E</a></li>
                <li><a href="#" >Samsing Mobile</a></li>
                <li><a href="#" >Micromaxi Mobile</a></li>
                <li><a href="#" >Nokian Mobile</a></li>
                <li><a href="#" >HTCK Mobile</a></li>
                <li><a href="#" >Sonyo Mobile</a></li>
                <li><a href="#" >Appleo Mobile</a></li>
                <li><a href="#" >LGG Mobile</a></li>
                <li><a href="#" >Karbonno Mobile</a></li>
            </ul>
        </div>
        <div class="col-sm-12">
            <ul id="trademark-laptop-list" class="trademark-list">
                <li class="trademark-text-tit">LAPTOPS::</li> 
                <li><a href="#" >Appleo Laptop</a></li>
                <li><a href="#" >Acero Laptop</a></li>
                <li><a href="#" >Samsing Laptop</a></li>
                <li><a href="#" >Lenov Laptop</a></li>
                <li><a href="#" >Sonyo Laptop</a></li>
                <li><a href="#" >Dello Laptop</a></li>
                <li><a href="#" >Asuso Laptop</a></li>
                <li><a href="#" >Toshibao Laptop</a></li>
                <li><a href="#" >LGG Laptop</a></li>
                <li><a href="#" >HPO Laptop</a></li>
                <li><a href="#" >Notebook</a></li>
            </ul>
        </div>
        <div class="col-sm-12">
            <ul id="trademark-watches-list" class="trademark-list">
                <li class="trademark-text-tit">WATCHES:</li>  
                <li><a href="#" >FCUKJ Watches</a></li>
                <li><a href="#" >Titan Watches</a></li>
                <li><a href="#" >Casioo Watches</a></li>
                <li><a href="#" >Fastracki Watches</a></li>
                <li><a href="#" >Timexe Watches</a></li>
                <li><a href="#" >Fossill Watches</a></li>
                <li><a href="#" >Diesel Watches</a></li>
                <li><a href="#" >Toshibao Laptop</a></li>
                <li><a href="#" >Luxury Watches</a></li>
            </ul>
        </div>
        <div class="col-sm-12">
            <ul id="trademark-shoes-list" class="trademark-list">
                <li class="trademark-text-tit">FOOTWEAR:</li>  
                <li><a href="#" >Shoes</a></li>
                <li><a href="#" >Casual Shoes</a></li>
                <li><a href="#" >Sports Shoes</a></li>
                <li><a href="#" >Adidas Shoes</a></li>
                <li><a href="#" >Gas Shoes</a></li>
                <li><a href="#" >Puma Shoes</a></li>
                <li><a href="#" >Reebok Shoes</a></li>
                <li><a href="#" >Woodland Shoes</a></li>
                <li><a href="#" >Red tape Shoes</a></li>
                <li><a href="#" >Nike Shoes</a></li>
            </ul>
        </div>
    </div><!-- /#trademark-text-box -->