<div id="trademark-box" class="row">
        <div class="col-sm-12">
			<ul id="trademark-list">
			    <li id="payment-methods">Accepted Payment Methods</li>
			    <li>
			        <a href="#"><img src="image/catalog/footer/trademark-ups.jpg"  alt="ups"/></a>
			    </li>
			    <li>
			        <a href="#"><img src="image/catalog/footer/trademark-qiwi.jpg"  alt="ups"/></a>
			    </li>
			    <li>
			        <a href="#"><img src="image/catalog/footer/trademark-wu.jpg"  alt="ups"/></a>
			    </li>
			    <li>
			        <a href="#"><img src="image/catalog/footer/trademark-cn.jpg"  alt="ups"/></a>
			    </li>
			    <li>
			        <a href="#"><img src="image/catalog/footer/trademark-visa.jpg"  alt="ups"/></a>
			    </li>
			    <li>
			        <a href="#"><img src="image/catalog/footer/trademark-mc.jpg"  alt="ups"/></a>
			    </li>
			    <li>
			        <a href="#"><img src="image/catalog/footer/trademark-ems.jpg"  alt="ups"/></a>
			    </li>
			    <li>
			        <a href="#"><img src="image/catalog/footer/trademark-dhl.jpg"  alt="ups"/></a>
			    </li>
			    <li>
			        <a href="#"><img src="image/catalog/footer/trademark-fe.jpg"  alt="ups"/></a>
			    </li>
			    <li>
			        <a href="#"><img src="image/catalog/footer/trademark-wm.jpg"  alt="ups"/></a>
			    </li>
			</ul> 
	</div>
</div> 