<div id="address-box">
    <a href="#"><img src="image/catalog/option5/logo.png" alt="" /></a>
    <div id="address-list">
        <div class="tit-name">Address:</div>
        <div class="tit-contain">Example Street 68, Mahattan, New York, USA.</div>
        <div class="tit-name">Phone:</div>
        <div class="tit-contain">+00 123 456 789</div>
        <div class="tit-name">Email:</div>
        <div class="tit-contain">support@business.com</div>
    </div>
</div> 
        