<div class="col-sm-3">
     <div class="widget-container">
         <h3 class="widget-title">Infomation</h3>
         <div class="widget-body">
             <ul>
                 <li><a class="location" href="#">2046 Blue Spruce Lane Laurel, tetxac, Orton Tolanto, Canada</a></li>
                 <li><a class="phone" href="#">0200 410-369-3920</a></li>
                 <li><a class="email" href="#">nfo@kutethemes.com</a></li>
                 <li><a class="mobile" href="#">Hotline: 090 999 8686</a></li>
             </ul>
         </div>
     </div>
 </div>