<div class="col-sm-3">
     <div class="footer-social">
         <ul>
             <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
             <li><a class="pinterest" href="#"><i class="fa fa-pinterest"></i></a></li>
             <li><a class="vk" href="#"><i class="fa fa-vk"></i></a></li>
             <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
             <li><a class="google-plus" href="#"><i class="fa fa-google-plus"></i></a></li>
         </ul>
     </div>
 </div>