<div id="home-slider">
    <div class="container">
        <div class="row">
            <?php if($displayed_vertical_menu) { ?>
                <div class="col-sm-3 slider-left">
                    <?php echo $Loader->block('module/verticalmenu')->setTemplate('vertical_menu.phtml')->setData($data)->toHtml(); ?>
                </div>
            <?php } ?>
            <div class="col-sm-<?php echo ($displayed_vertical_menu ? '9 shift-left-1' : '12')?> header-top-right">
                <div class="homeslider">
                    <div class="content-slide">
                        <ul id="contenhomeslider">
                            <?php foreach ($banners as $banner) { ?>
                                <li class="item">
                                    <?php if ($banner['link']) { ?>
                                        <a href="<?php echo $banner['link']; ?>"><img src="<?php echo $banner['image']; ?>" alt="<?php echo $banner['title']; ?>" class="img-responsive" /></a>
                                    <?php } else { ?>
                                        <img src="<?php echo $banner['image']; ?>" alt="<?php echo $banner['title']; ?>" class="img-responsive" />
                                    <?php } ?>
                                </li>
                            <?php } ?>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>