<div class="col-left-slide left-module">
    <ul class="owl-carousel owl-style2" data-loop="true" data-nav = "false" data-margin = "0" data-autoplayTimeout="1000" data-autoplayHoverPause = "true" data-items="1" data-autoplay="true">
        <?php foreach ($banners as $banner) { ?>
        <li><a href="<?php echo $banner['link']; ?>" title="<?php echo $banner['title']?>"><img src="<?php echo $banner['image']; ?>" alt="slide-left"></a></li>
        <?php } ?>
    </ul>
</div>