<script type="text/javascript" src="catalog/view/theme/kute/js/imagesloaded.pkgd.min.js"></script>
<script type="text/javascript" src="catalog/view/theme/kute/js/appear/jquery.appear.min.js"></script>
<script type="text/javascript" src="catalog/view/theme/kute/js/jquery.bxslider/jquery.bxslider.min.js"></script>
<script type="text/javascript" src="catalog/view/theme/kute/js/owl.carousel/owl.carousel.js"></script>
<script type="text/javascript" src="catalog/view/theme/kute/stylesheet/jquery-ui/jquery-ui.min.js"></script>
<script>
    $.fn.button = function(option)
    {
        return this;
    }
</script>
<script type="text/javascript" src="catalog/view/theme/kute/js/jquery.actual.min.js"></script>
<script type="text/javascript" src="catalog/view/theme/kute/js/jquery.elevatezoom.js"></script>
<?php echo $Loader->block('common/footer_'.$current_theme.'')->setTemplate('footer/'.$current_theme.'.phtml')->setData($data)->toHtml(); ?>
<a href="#" class="scroll_top" title="Scroll to Top" style="display: inline;"><?php echo $translator->_('Scroll')?></a>