<form class="form-inline" onsubmit="return false;">
    <div class="form-group form-category">
        <select class="select-category">
            <option value="-1" <?php echo ($category_id == '-1' ? 'selected="selected"' : ''); ?>><?php echo $translator->_('All Categories'); ?></option>
            <?php if(count($categories) > 0) {?>
                <?php foreach($categories as $category) {?>
                    <option value="<?php echo $category['category_id']?>" <?php echo ($category_id == $category['category_id'] ? 'selected="selected"' : ''); ?>><?php echo $category['name']?></option>
                <?php } ?>
            <?php } ?>
        </select>
    </div>
    <div class="form-group input-serach">
        <input type="text" name="search"  placeholder="<?php echo $translator->_('Type Your Keyword...')?>" value="<?php echo $search; ?>"/>
    </div>
    <button type="button" class="pull-right btn-search"><i class="fa fa-search"></i></button>
</form>